### ISSUE TITLE
Add recipients not working

### ISSUE THREAD

**Issue by jkpatil211** [sendgrid/docs#1025]
I tried to add recipient using api
I used following JSON data
data[]={"email":"anything@gmail.com","name":"xyz","phone":"9579289528"}

but It does not insert anything.
When I removed other keys and used this:
data[]={"email":"anything@gmail.com","name":"xyz"}
it worked.
So basically the api is not accepting other fields.

But it is clearly written in docs that You can specify other fields as key.

https://sendgrid.com/docs/API_Reference/Marketing_Emails_API/emails.html

**Comment by jkpatil211** [comment]
Waiting For support

**Comment by mbernier** [comment]
I believe what is going on here is that you don't have the "phone" field defined for the list you are adding the recipient to. 

For more in depth support with the SendGrid product, since I have no access to your email address via github and therefore cannot start a support ticket for you, can you please email support@sendgrid.com? Our amazing support team will help you much more efficiently than I can via a github issue. Please feel free to copy me: [my github username] @ sendgrid dot com on your request.

Thanks!!
