### ISSUE TITLE
"URI Parameter" term is confusing

### ISSUE THREAD

**Issue by jacobmovingfwd** [sendgrid/docs#1360]
On https://sendgrid.com/docs/API_Reference/Web_API_v3/Settings/enforced_tls.html#-PATCH
the table column is called "uri parameter", which makes me think I should be adding them to the URI as `?` arguments. These actually need to be JSON body arguments to update properly.

**Comment by thinkingserious** [comment]
Hello @jacobmovingfwd,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs

**Comment by jacobmovingfwd** [comment]
still an issue.

**Comment by ksigler7** [comment]
Hey @jacobmovingfwd, thanks for opening this back up! As you may know, right now, we're in the process of migrating our API doc to a new format. It looks like we have this issue fixed in the new format: https://sendgrid.api-docs.io/v3.0/settings-enforced-tls/update-enforced-tls-settings. I'm going to close this issue again because we're not really updating out old v3 doc anymore since we're on the verge of sunsetting it.
