### ISSUE TITLE
CORS header incorrect

### ISSUE THREAD

**Issue by tcdevs** [sendgrid/docs#1417]
I have the same problem as @heycait on issue #370.

Im using the url https://api.sendgrid.com/api/mail.send.json with my custom AngularJS factory to send an email. This **will** work but i still get a CORS error. It will send the email accordingly.

This are the custom settings for the header in the AngularJS $http service:

```
headers: {
    'Content-Type': 'application/json' , 
    'Access-Control-Allow-Origin': 'http://sendgrid.com',
    'Access-Control-Allow-Methods': 'POST, GET, OPTIONS',
    'Access-Control-Allow-Headers':'X-Requested-With'	
}
```

or with wildcard

```
headers: {
    'Content-Type': 'application/json' , 
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'POST, GET, OPTIONS',
    'Access-Control-Allow-Headers':'X-Requested-With'	
}
```
With both of the  example headers i get the following error message:

```
Response to preflight request doesn't pass access control check: 
The 'Access-Control-Allow-Origin' header has a value 'https://sendgrid.com' 
that is not equal to the supplied origin. Origin 'http://192.168.0.25:8031' is 
therefore not allowed access.
```

The problem seems to be the  'Access-Control-Allow-Origin ' header on your domain need to be an wildcard instead of 'http://sendgrid.com'

Can this problem be fixed? Thanks for the help in advance.

**Comment by cupcakedream** [comment]
Hey has this been fixed yet? I'm running into CORS issues with the API

**Comment by bstaruk** [comment]
I am also waiting for a fix, for this issue.

**Comment by scottmahr** [comment]
Also waiting on this. Is there a good work around?

**Comment by Jimmathy** [comment]
I think I'm having the same issue with my Laravel API...

**Comment by mbernier** [comment]
Hey guys, we're not ignoring you. I am working through this issue, checking with my teams to figure out what's going on.  I do need some extra information if you can provide it. 

@Jimmathy are you getting a specific error? can you please provide it? 

@bstaruk if that tool is making the call from the browser, the CORS rejection is likely legitimate as a browser to API call is potential security concern for the user. We will ask customers not to make JS calls to the API from their front end website, but rather to make an AJAX call to a server side script, as the browser request to SendGrid means there is likely an exposed API KEY in the mix.

**Comment by Zetberg** [comment]
+1
same issue, PHP Slim API with AngularJS frond end

**Comment by tcdevs** [comment]
@mbernier any news yet?

**Comment by UCJava** [comment]
Hi Guys,
  The issue is "Access-Control-Allow-Origin" header needs to be exposed and set to "*" on the https://api.sendgrid.com/api/mail.send.json API response . Are you still trying to figure out how to change the response ? or is this on the way to be fixed ? This will allow people to use JS libraries directly from browsers , the request seems to go through but the response is not getting acccepted due to CORS. Also I couldn't get the AJAX call with the Authorization header being the API Key bearer token work as well. Is there an issue with that as well ?

**Comment by abernix** [comment]
Ran into this today while adding support for SG as their competitor is changing their pricing options a bit.  I'm using this in a browser extension that (safely) stores the users individual credentials.  Of course it's their prerogative to set the `Allow-Control-Allow-Origin` as they have, it's definitely a bit different than what I expect out of a public API (see, I dunno, [Github API for example](https://developer.github.com/v3/)).

Additionally, strange that the API doesn't respond properly to `OPTIONS` requests.  Also, requires authorization token and `to` address to be set?  It appears to be implemented identically to `POST` and not work as expected for a REST API.

The (not mentioned) competitor used the following CORS rules, allowing this to work from a browser extension.
```
Access-Control-Allow-Credentials: false
Access-Control-Allow-Headers: Content-Type
Access-Control-Allow-Methods: POST, GET, OPTIONS
Access-Control-Allow-Origin: *
```

SendGrid is currently using only `Access-Control-Allow-Origin: https://sendgrid.com`

**Comment by derekrliang** [comment]
Experiencing same issue as well...

**Comment by levivm** [comment]
I have the same issue using V3 API.

**Comment by Zetberg** [comment]
after over 6 months still not fixed, so here is solution:

- Amazon SES
- Postmark
- SocketLabs
- MailJet
- ElasticEmail

**Comment by mbernier** [comment]
There are a couple reasons why we have this functionality the way we have it:

1. We do not want to open up any users or ourselves to the types of interference that this header was designed to prevent.
2. It is not a good idea to have email sending built into a front-end / browser app, because it is likely that your keys, being sent to the API by the customer's browser means your key is your customer's key. That's not great because someone can start sending all kinds of emails through your account once they have your keys.

Having said that, we completely understand that tools like Postman, Stoplight, and others are browser based tools that serve a very specific and useful purpose. We use them too!! So, we completely understand the frustration that comes when something doesn't "just work."

As you know, there is always a balance between security and usability, often times we can find a nice way to make them both win. CORS functionality being a limiting factor for usability on our API is something that I personally have been negotiating and advocating about well before this ticket was opened.

Having said all of that, I brought this back around with both my Infosec and Ops teams to figure out what their official stance is going to be. They told me that they have a solution and I hope to have the official answer and the updates in place very soon (not another 6 months).

**Comment by jrsteele23** [comment]
I understand how awesome it is to be able to send emails from a front-end Angular application and the client browser but setting 'Access-Control-Allow-Origin' to * seems a bit extreme. While I sure many of the developers above requesting the change understand the security implications many developers do not.

I'm hoping the solution they are working on is a custom [sub]domain per customer that send the  'Access-Control-Allow-Origin' set to a setting that each customer can customize (in their SendGrid account setup). I think a solution like this would be a good balance between security concerns and functionality.

**Comment by UCJava** [comment]
While the security issue is well known to everyone, there are many secure
REST services out there for similar service. The way web technology has
revolved now it is more than a necessity. Front End frameworks are widely
used, not all websites require a back end server; isn't it extreme to have
a server running for just communicating with a mail provider service ?

**Comment by jrsteele23** [comment]
I would be cautious with "the security issue is well known to everyone". I wish that were true but all you need to do is hop over to stackoverflow to see what/that some inexperienced developers aren't aware of security issues and would/could easy server the API up over http (instead of https). So while I wish it wasn't so, there is still security issues to be concerned about especially when API calls also have an actually cost associated with them and others could cause others to incur those costs. I don't think it's extreme to have a proxy server running to ensure security. Again opening up the 'Access-Control-Allow-Origin' to * is a bit extreme. I'm guessing they are working on a way to allow each customer to define their own ''Access-Control-Allow-Origin'' and have calls to/from their javascript scripts from a "custom" [sub]domain.

**Comment by mbernier** [comment]
Oh, I like that idea @jrsteele23. I'll write it down and bring it up for future improvements.

**Comment by mbernier** [comment]
More information: We should have a fix in the next couple of weeks, it is being put in the queue of things to take live. I will update this thread when an update is in place.

**Comment by irthos** [comment]
+1 emailing is supposed to be easy and the developers choice between browser for loose emails and server for secure emails

**Comment by holgersindbaek** [comment]
+1 When's the functionality coming out?

**Comment by mbernier** [comment]
I promised an update as soon as I could - it is being worked on this week. I should be able to announce that this is done very soon. 

Sorry for the delay!

**Comment by tcdevs** [comment]
It took some time  :smile: But thank you @mbernier. I will close this issue.

**Comment by vvillait88** [comment]
@mbernier Any updates to this?

**Comment by mbernier** [comment]
The CORS header issue has been rectified some time ago. I updated another thread, but missed this one. I am REALLY sorry about that!! 

You should be able to make calls to the API from browsers now. Please let me know if you don't see this working...

@OlleMattsson the 405 method not allowed for OPTIONS on v3/mail/send is because that method specifically is not set up. v3/mail/send only accepts POST.

**Comment by OlleMattsson** [comment]
@mbernier I couldn't find any specific documentation on how to call the API from browsers. Or I have been looking in the wrong place 0.o Perhaps you can point we in the right direction?

When POSTing to v3/mail/send with authorization header, chrome preflights that request with an OPTIONS request. As far as I know that can't really be circumvented...

**Comment by abernix** [comment]
@OlleMattsson A request is only preflighted under the following circumstances:

> * It uses methods other than GET, HEAD or POST. Also, if POST is used to send request data with a Content-Type other than application/x-www-form-urlencoded, multipart/form-data, or text/plain, e.g. if the POST request sends an XML payload to the server using application/xml or text/xml, then the request is preflighted.
> * It sets custom headers in the request (e.g. the request uses a header such as X-PINGOTHER)

([quoted from Mozilla CORS reference](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Preflighted_requests))

**Comment by OlleMattsson** [comment]
This is the particular request I'm trying to make (from the browser client)

POST: https://api.sendgrid.com/v3/mail/send
Authorization: 'Bearer ' + API_KEY
Content-Type: 'application/json'

Is this incorrect or incomplete?

**Comment by abernix** [comment]
@OlleMattsson Yeah, it would almost work, but when using `application/json` with a `POST` you cannot avoid the `OPTIONS` header sent by the browser – which they don't support (something I mentioned as peculiar in my [original comment in April](https://github.com/sendgrid/docs/issues/1417#issuecomment-214795051)).

But honestly, I don't believe this issue was ever resolved.  I never got it working with SendGrid but it worked immediately when I tried another provider.  I never tried just using the wrong `Content-Type` (maybe plain `text/plain` or something?) to see if SendGrid would still notice it was JSON, but that could be an option.

**Comment by OlleMattsson** [comment]
@abernix the `text/plain` trick would otherwise work, but in this particular case we also need the `Authorization` header which causes the request to be preflighted.

**Comment by abernix** [comment]
@OlleMattsson While I have not tested it, the `Authorization` header should not be considered a "Custom" header as it is a permanent part of the HTTP spec.  Therefore, it should not trigger the preflight.  Really though, the API should probably support `OPTIONS`.

**Comment by OlleMattsson** [comment]
@abernix  that's interesting. Adding the authorization header definately is causing the OPTIONS request. Maybe it's because i'm using legacy jQuery for requests (this old project that got dumped in my lap a few days ago)...

**Comment by mbernier** [comment]
Thanks for the conversation everyone!! This is really helping me understand the issue around OPTIONS. I am adding this to the todo list for the team. I'll let you know what I find out. 

@OlleMattsson 
We have been using Stoplight.io and Postman, without seeing these issues. Are you using Chrome itself or another plugin within Chrome to make these calls?

**Comment by osmanra2** [comment]
I get these errors when I am attempting to process through angularjs on client. Not sure if this will help at all. 

```
$http(
            {
                "method": "POST",
                "url": "https://api.sendgrid.com/v3/mail/send",
                "headers": {
"Content": "application/json",                    
"Access-Control-Allow-Origin": "*",
                    "Authorization": "Bearer " + api_key
                },
            data: {
  "personalizations": [
    {
      "to": [
        {
          "email": webmaster
        }
      ],
      "subject": subject
    }
  ],
  "from": {
    "email": email
  },
  "content": [
    {
      "type": "text/plain",
      "value": comments
    }
  ]
}

            }
        ).then(function(success) {
            console.log("SUCCESS " + JSON.stringify(success));
        }, function(error) {
            console.log("ERROR " + JSON.stringify(error));
        });

      }
```

```
[Error] Failed to load resource: the server responded with a status of 405 (Method Not Allowed)
[Error] Failed to load resource: Preflight response is not successful
[Error] XMLHttpRequest cannot load https://api.sendgrid.com/v3/mail/send. Preflight response is not successful
```

`ERROR {"data":null,"status":-1,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"url":"https://api.sendgrid.com/v3/mail/send","headers":{"Access-Control-Allow-Origin":"*","Authorization":"Bearer xxx","Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8"},"data":{"personalizations":[{"to":[{"email":"xxx"}],"subject":"xxx", Organization: "sds"}],"from":{"email":"xxx"},"content":[{"type":"text/plain","value":"xxx"}]}},"statusText":""}`

**Comment by abernix** [comment]
Preflight requests (e.g. `OPTIONS`) are only necessary in situations where trust is not expected – in fact, that is the entire purpose of the [`OPTIONS`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS) method, as a part of the CORS negotiation process.  My Postman is a native OS X app now, so this would be absolutely unnecessary.  I think in the past Postman was a Chrome App (or something like that), so similarly, Chrome considered it a trusted resource, thus, no need to handshake with `OPTIONS`.

You can probably fake the preflight somehow for testing purposes, but you should probably familiarize yourself further about what `OPTIONS` does and what it's supposed to do.  Hope this helps.

**Comment by iKarl** [comment]
Hello, I have the same problem when I make a request to /v3/mail/send

Just when I put the header "Authorization" fails the request.

The most curious of this is, if I make the request in Postman with: Authorization: "Bearer XXXX", the request is send as POST.

Example with Postman:

<img width="822" alt="captura de pantalla 2016-11-10 a las 6 05 46 p m" src="https://cloud.githubusercontent.com/assets/1570331/20199764/831b5870-a772-11e6-9e5e-c0c17b9c0df1.png">

Success!

But if done with Angular, send the request as "OPTIONS"

Example with angular and Authorization:

$http({
      method: "POST",
      url: "https://api.sendgrid.com/v3/mail/send",
      headers: {
           "Authorization": "Bearer XXX",
           "Content-Type": "application/json"
      },
      data: {...}
});

Error, Bad Request OPTIONS not allowed!

Example 2 with angular without Authorization:

$http({
      method: "POST",
      url: "https://api.sendgrid.com/v3/mail/send",
      headers: {
           "Content-Type": "application/json"
      },
      data: {...}
});

Success, but sendgrid response: "401 Unauthorized"

It is Sengrid or Angular problem!

Sorry for my english.

**Comment by OlleMattsson** [comment]
@iKarl, @mbernier  This is a feature of the browser. There's no legit workaround, nor should there be. This is also why it works in Postman (because it's not a browser and it inherently trusts that the requests you are trying to make are legit). 

The "problem" if you will, is that sendgrid's API currently does not handle OPTIONS requests. Maybe this will be fixed sometime in the future. In the meantime i recommend perusing the http spec on OPTIONS  (section 9.2): https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html 

My solution in this case is a small node server that handles and relays the request to sendgrid. Since node (like postman) is not a browser environment, it too can make POSTs with custom headers without triggering an OPTIONS preflight request first. Please note that this is indeed the correct way to do this, since calling the sendgrid API from the client would leave your (secret!) API key open to the wild wild web. In that regard the current implementation by sendgrid is totally legit. Perhaps somewhat cumbersome, but legit. And it forces us to implement things the right way =)

**Comment by abernix** [comment]
> Please note that this is indeed the correct way to do this, since calling the sendgrid API from the client would leave your (secret!) API key open to the wild wild web. In that regard the current implementation by sendgrid is totally legit. Perhaps somewhat cumbersome, but legit. And it forces us to implement things the right way

This is a heavy-handed declaration and is simply not true.  It is definitely a "Fort Knox" way to make sure that nobody accidentally does what you've suggested in that particular configuration, but there are secure ways to implement this in particular environments where it might be necessary.

It could easily be argued that if you have a "small Node server" relaying the request that it might be vulnerable to all sorts of misuse even without exposing your API key.  I think any user who would be capable of insecurely leaking their API key on the client would be just as capable of setting up an insecure Node relay server.  Please understand that I'm not suggesting this is the case in your situation, but if care is not taken and security is not understood anything can be misused.

@iKarl If you are implementing (whatever you are building) in a particularly secure environment, what you're doing may be harmless, but you need to take great care to ensure that is the case.  If this is a public service, you would be advised to do that mail-sending under different conditions (server side, for example) as recommended.

But if you are building an offline app which doesn't have a server but needs to send mail, you might have the user enter their SendGrid API credentials in a secure environment that is only available to a particular browser, app or otherwise sandboxed environment.  This is where you would need this feature.  I don't feel its any more secure to send your request off to a relay server in this scenario.

I found 5 other major e-mail players in the industry that this worked with on the first try.  [Stripe](https://stripe.com/), the credit card processor has an API which [supports CORS](https://stripe.com/docs/api?lang=php#intro) – just saying.  If SendGrid doesn't want to support `OPTIONS`, that's absolutely fine.  It's a very secure approach.  However, they can undo any of the work that they did to "solve" this issue because it worked in the way you just recommended before the issue was even opened and it cannot be solved without fully implementing `OPTIONS`.

Anyhow, I'm done needing this feature and implemented it elsewhere so this will likely be the last of my comments on the matter.

**Comment by iKarl** [comment]
@abernix Thank you very much for your comment and suggestion, I will try other systems like Stripe.

@OlleMattsson Thanks for the comment, of course we are forced to do things the right way, we will have to implement a small instance with node.js in what we see a better solution to this, thank you very much.

**Comment by mbernier** [comment]
I have escalated the issue and will let you all know what the word is on getting it fixed. 

Sorry for the trouble!

**Comment by mbernier** [comment]
The team is picking it up soon and will have this fixed. Sorry for the trouble. 

Also, we absolutely appreciate all of your willingness to share and let us know exactly what you're working on and why this is a problem. It helps us to prioritize and explain the issue to our teams.

**Comment by codarrior** [comment]
Please have this problem fixed as soon as possible. I'm currently making front-end application using angular without web server but I've already integrated Sendgrid API into the application without working yet. Hope your team fix it soon so that I don't need to change my mailing service before publishing the app.

**Comment by matthieunelmes** [comment]
Any update on this?

Kinda glad/hella disappointed I found this thread.

upside: after 2 days I'm not loosing my mind and there is a genuine CORS issue
downside: now I have to potentially look at another email provider for my app.

**Comment by mbernier** [comment]
@matthieunelmes My understanding is that this is in the next sprint to be completed. It should be live soon.

**Comment by mbernier** [comment]
After many discussions on this, I have questions. 

As @OlleMattsson mentioned, having your front-end application using an API Key is insecure and allows anyone using that application to access the keys using their browser. The use case of a backend application is valid use case, however by allowing this we open up many developers who might not fully understand CORS and application security to expose their keys.

@matthieunelmes @codarrior @iKarl are you building internal only applications or are they facing the public? 

My ignorance on Angular is showing: How would you secure your other API keys in Angular? 

Thanks!

**Comment by medlmichael** [comment]
Hi Everyone,

I'm trying to do what you are mentioning and having the same issues.  Any fix for this issue yet?

Thank you!

**Comment by codarrior** [comment]
When can you fix this problem? It has been very long since you mentioned "soon". I don't want insecure Key exposure at all. But there should be some option for this so as to enable front-end coding.

**Comment by iKarl** [comment]
@mbernier Hi!

I am development an mobile app on Ionic with Firebase and use $http in AngularJs to call API sendgrid.

**Comment by MaxPleaner** [comment]
I've encountered this issue in a server-side environment. I'm figuring my HTTP Client (the Ruby gem "mechanize") is sending a preflight request for POST with the auth & json content-type headers, and that's why it's not working. I will see if I can configure the HTTP Client to not send the OPTIONS request.

**Comment by matthieunelmes** [comment]
Almost a year later, still hitting this problem...

**Comment by mbernier** [comment]
The reason there is a CORS header is not as straightforward as it would seem on the surface. APIs should be callable from everywhere, right!?

This is the result of SendGrid being a compliant and contributing member anti-spam and anti-malware compliance group, [M3AAWG](https://www.m3aawg.org/). 

"How the heck does this apply to my problem!?", you might be saying ... please stay with me. 

Every time someone sends an email, email blacklist organizationss, spam filters, and anti-malware groups are paying attention and gather information. When they see spam or phish coming from the same IPs over and over, they start blocking the IPs and the IP ranges, to protect the world's inboxes. 

As a preventative measure, to make it so that API keys are not exposed inside of browser-based applications, we have disallowed CORS type requests on our API. This, despite the frustration this decision causes, is to protect your account, your API Key, and SendGrid all in one setting on the SendGrid API.

It sucks, and trust me, I fought our InfoSec and Compliance teams on this - but once I got the explanation, I had to agree with them about their decision to disallow CORS requests.

Our suggestion is to create a server-side application that stores your API keys and make requests to that application from your browser-based app (and actually from mobile apps), to send your email.

I hope this helps, even though it is definitely not the answer anyone was hoping for.

**Comment by jrsteele23** [comment]
@mbernier Thanks for the info and update.

I totally understand the concern if an enduser making use of a shared IP plan. I'm guessing most folks wanting this CORS functionality aren't interested in paying much for it. But perhaps SendGrid and your InfoSec and Compliance teams might be amendable to allowing/implementing a plan or add on that would allow for this functionality. I would suggest that to enable this functionality the customer would need to pay for a dedicated IP and prevent CORS requests from going out through non-dedicated IPs.

Truthfully, I don't see that happening. Luckily, serverless functions are all the rage today and should make it fairly trivial to develop an AWS Lamba function, Azure Function App, or GCP Cloud Function to handle the actual storing of the API key and sending on a "hosted backend".

**Comment by matthieunelmes** [comment]
Yeah, I kinda get the Compliance thing. Particularly with everyone getting nervous about GDPR.

In the 2 hours since I posted, I've gone and written a NodeJS app to handle sending emails, so it's no massive hardship. I just found it entertaining that I found this thread again!

**Comment by mbernier** [comment]
@matthieunelmes I am not sure if this is something you would be willing to share, but we would love to see something like that in the library... If people can do something similar very easily, it would be really awesome.

**Comment by matthieunelmes** [comment]
@mbernier 
The NodeJs library already exists here:
https://github.com/sendgrid/sendgrid-nodejs

I guess I could take a look at writing an example/tutorial. Although for my particular setup I'm integrating with firebase to pull in different user data to use in template substitutions, So I'm also handling that in the backend which might be a bit overkill for some people.

**Comment by mbernier** [comment]
@matthieunelmes If you were willing to write up the basics of how you set up the Mail/send request part in Node, as an issue [in the nodejs repo](https://github.com/sendgrid/sendgrid-nodejs), I would be grateful. Then, if someone wants to add it in or reproduce it on their own, it would be much easier!

**Comment by mbernier** [comment]
@david-roth we specifically only allow our docs, because it lets people try the API without writing any code and we can generally control how the API Keys are used (you use it in your own session, we never see it). However from a 3rd party code standpoint, we cannot control how people distribute their keys - so it makes it a compliance issue.

One thing we are working with a current customer on is information on how they got around this issue through mobile apps and browser-only applications. Once we have that information written up, I will personally come back to this thread and add the link to the info! It's a really slick solution.

**Comment by redaxmedia** [comment]
## Finally

Here comes a one click solution!

1. Deploy your instance of [SendGrid Proxy](https://github.com/redaxmedia/sendgrid-proxy) to Heroku
1. Done (Really)

## How it works

1. It creates a node powered http proxy using [express-http-proxy](https://www.npmjs.com/package/express-http-proxy)
1. It adds needed headers such as `Authorization` and `Content-Type`
1. It overrides `Access-Control-Allow-Origin` to `*` to make your browser `CORS` warning free

See how the [magic](https://github.com/redaxmedia/sendgrid-proxy/blob/master/src/core.js#L17-L39) is working. You like it? Give it a star...

Feedback welcome

**Comment by JerryGreen** [comment]
@redaxmedia looks pretty... Looks like it does not receive `"Content-Type": "application/json"` fetch requests :(

Error on proxy server side:

```
$ /Users/jerrygreen/projects/project/node_modules/.bin/sendgrid-proxy
⠧ Listen on :3001Error: Parse Error
    at TLSSocket.socketOnData (_http_client.js:439:20)
    at TLSSocket.emit (events.js:159:13)
    at addChunk (_stream_readable.js:265:12)
    at readableAddChunk (_stream_readable.js:252:11)
    at TLSSocket.Readable.push (_stream_readable.js:209:10)
    at TLSWrap.onread (net.js:608:20)
```

Still useful though, it's working for simple request when I do `JSON.stringify()` on the body. Thank you!

**Comment by redaxmedia** [comment]
Hello JerryGreen,

I'm pretty sure that I send the correct header according to the docs:

```
curl -X "GET" "https://api.sendgrid.com/v3/templates" -H "Authorization: Bearer Your.API.Key-HERE" -H "Content-Type: application/json"
```

Related code of sendgrid-proxy:

```
proxyReqOpts.headers['Authorization'] = 'Bearer ' + runArray.apiId;
proxyReqOpts.headers['Content-Type'] = 'application/json';
```

Maybe you are doing something wrong on your side? Anyway, glad that I worked for you.

**Comment by JerryGreen** [comment]
@redaxmedia just try using `fetch` with "Content-Type": "application/json"

it's error on proxy side, I suppose. Example:

```
    const headers = new Headers({
      "Content-Type": "application/json"
    })

    const requestOptions = {
      method: 'POST',
      mode: 'cors',
      headers,
      body
    }

    fetch('http://myproxy.com/v3/mail/send', requestOptions)
```

I don't _really_ need that since I can send a simple string & it works. Just an odd moment.

Btw, working example:

```
    const requestOptions = {
      method: 'POST',
      mode: 'cors',
      body: JSON.stringify(body)
    }

    fetch('http://myproxy.com/v3/mail/send', requestOptions)
```

**Comment by redaxmedia** [comment]
There is nothing wrong with sendgrid-proxy, I double check it on a live project and using RestClient (Firefox Plugin) and it returns the correct `Content-Type`.

You have to send your request body as JSON of course - the proxy does not convert that for you, it just sends the correct headers.

**Comment by JerryGreen** [comment]
Oh you mean I need to JSON.stringify in any case? Lol. Of course! Silly mistake... I always used a wrapper without that need before, forgot how it really works.

The proxy is great, thank you!

**Comment by brachi-wernick** [comment]
@redaxmedia works! amazing thank you!

**Comment by ChristopherJohnson25** [comment]
@redaxmedia is the sendgrid proxy still working? Having some troubles. Is anyone else using this successfully currently?

**Comment by MD3XTER** [comment]
> @redaxmedia just try using `fetch` with "Content-Type": "application/json"
> 
> it's error on proxy side, I suppose. Example:
> 
> ```
>     const headers = new Headers({
>       "Content-Type": "application/json"
>     })
> 
>     const requestOptions = {
>       method: 'POST',
>       mode: 'cors',
>       headers,
>       body
>     }
> 
>     fetch('http://myproxy.com/v3/mail/send', requestOptions)
> ```
> I don't _really_ need that since I can send a simple string & it works. Just an odd moment.
> 
> Btw, working example:
> 
> ```
>     const requestOptions = {
>       method: 'POST',
>       mode: 'cors',
>       body: JSON.stringify(body)
>     }
> 
>     fetch('http://myproxy.com/v3/mail/send', requestOptions)
> ```

For me it worked only with `mode: "no-cors"`

**Comment by redaxmedia** [comment]
@MD3XTER Well, this is an issue with your browser and the `fetch()` API...

BROWSER  < - (1) - > PROXY < - (2) ->  SENDGRID

The magic of this proxy happens only on part 2 - it does not influence the [request mode](https://developer.mozilla.org/en-US/docs/Web/API/Request/mode) of the browser.
