### ISSUE TITLE
Sendgrid API Reference

### ISSUE THREAD

**Issue by mijphys** [sendgrid/docs#2016]
General Comment:  Python Sendgrid API is the worst.  Documentation is very poor - incorrect or incomplete.  No real explanation or examples for Sendgrid customers who will require both html and text content, not to mention headers beyond simple to-from.  I use Sendgrid to support business activities for my employer, not waste time with classroom exercises.  Speaking of, the JSON examples provided have overloaded headers like "subject" and "from" that appear in "personalization" with no explanation as to what might happen if "subject" or "from" is defined one way outside "personalization" and then another way inside "personalization" for the same message.  SendgridAPIClient is a thin wrapper around Python's HTTP Client, but normal POST requests to /v3/mail/send URL don't work and in some cases produce 4xx errors not documented, even though the CURL examples indicate that simple POST requests will work.  

I would have been happy if a simple POST request functioned as intended, using any mechanism I want, instead of providing a bloated interface with inconsistent behavior and results depending on which page of the v3 API documentation I pay attention to.  I am incredibly disappointed in Sendgrid's failures to provide a decent service/product to their paying customers.

Whoever wrote the code must also be confused about how to process a Reply-To header, because "replyto" does not work correctly and "reply_to" throws exceptions.  The reason I bring up this particularly pathetic example is because the exceptions come from within the Sendgrid Python library itself - When I create a Mail object and then attempt to send it with a Reply-To header, the library attempts to access a non-existent "headers" attribute - meaning the library authors are attempting to access class variables not present in the class definition.  This level of sloppiness is inexcusable.  I can choose to ignore the Reply-To header altogether, or just accept that if I attempt to include the header it will not function as intended.

The name of the header itself is not even "replyto" or "reply_to" - it's "Reply-To", meaning that Sendgrid's developers piled on a layer of complexity that they simply failed to implement correctly.  Any number of tests would have caught this failure - for example, pressing the "Reply" button on any email client and checking to see if the address matches.  Considering that Sendgrid's product is email, it is not outrageous to expect that Sendgrid's developers should read the headers of an email message their code produces.  This is the kind of work I would expect from a lazy college student, so to see it here is very disappointing.

**Comment by thinkingserious** [comment]
Hello @mijphys,

Thank you very much for the detailed feedback, it is greatly appreciated!

First, a bit of context: We took a few steps back with all our libraries to decouple them from the v2 mail send endpoint and add support for all the v3 web API endpoints. It is the first of many iterations and we need your help to assist with prioritization. Feedback like this is helpful for us to zero in on the issues that need attention first. I've recently updated the README to reflect this better.

Additionally, within a matter of days we will be exposing our [roadmap on GitHub](https://github.com/sendgrid/sendgrid-python) to continue our goal of community driven, SendGrid led libraries.

Following is an attempt to cover the points you have addressed directly:

1. Documentation

So far, the documentation for the library is here:

- README: https://github.com/sendgrid/sendgrid-python
- USAGE: https://github.com/sendgrid/sendgrid-python/blob/master/USAGE.md
- Examples: https://github.com/sendgrid/sendgrid-python/tree/master/examples

We have received a great deal of constructive feedback on the documentation and we are excited to begin our iterations. This is one of the items that will be listed on the public roadmap. Specific use cases and ideas are welcome.

I hear you load and clear regarding more explanation on usage within the library documentation. Right now, we have fragmentation, with some documentation at docs.sendgrid.com and some in the SendGrid library GitHub repo. We want you to be able to access complete documentation wherever you need it. This might entail some duplication, but sometimes that is necessary for a smoother experience.

Also, we are very happy to help with your specific issue. If you could provide some sample code with an explanation of what you need to execute, we can help you get going.

2. Simple POST

We have recently [updated the README](https://github.com/sendgrid/sendgrid-python#without-mail-helper-class) to show how to interact with the endpoints without the helper. As we iterate on the helper classes, we hope it will be much more convenient to use them vs. interacting with the HTTP client directly.

3. Reply-To

I'm not quite following on this topic. Since we are speaking in the context of the libraries, I'm assuming you are referring to setting the Reply-To header. In that case:

[Here is an example](https://github.com/sendgrid/sendgrid-python/blob/master/examples/helpers/mail/mail_example.py#L119) of setting the Reply-to using the helper, and [here](https://github.com/sendgrid/sendgrid-python/blob/master/examples/mail/mail.py#L132) directly. 

If my assumption is incorrect, we would appreciate further detail here so we can properly address the issue.

4. Error Handling

While we are looking forward to implementing a robust error handling layer as part of our roadmap, you can now access errors with a try/except as demonstrated [here](https://github.com/sendgrid/sendgrid-python/blob/troubleshooting/TROUBLESHOOTING.md#error-messages).

With Best Regards,

Elmer Thomas
Developer Experience Engineer | Product

**Comment by thinkingserious** [comment]
Hello @mijphys,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
