### ISSUE TITLE
Request body is missing in documentation for adding IP address to Pool

### ISSUE THREAD

**Issue by morgen-peschke** [sendgrid/docs#2250]
https://sendgrid.com/docs/API_Reference/Web_API_v3/IP_Management/ip_addresses.html

The section for adding an IP address to a pool is missing the request body section. The missing section should probably be:

``` json
{
  "ip": "000.00.00.0"
}
```

**Comment by ksigler7** [comment]
hey @morgen-peschke, thanks so much for pointing this out! We're not going to fix this right now because we're currently in the process of migrating to a new format for our API docs. Here's the new page for POST ip pools, and it does include a correct request body example: https://sendgrid.com/docs/API_Reference/api_v3.html
