### ISSUE TITLE
Event Webhook inconsistencies

### ISSUE THREAD

**Issue by jacobmovingfwd** [sendgrid/docs#238]
http://community.sendgrid.com/sendgrid/topics/inconsistencies_with_the_events_notification_webhook_documentation

a: I think sg_event_id is an internal tag only; I just did a Test Post, and it's not on any of the events.

b: smtp-id should be on all delivery events, and needs to be documented. This is an id attached by the originating system, so is a good way to trace the full message.

c: sg_message_id is our internal metric, and not sure why it's being transmitted,. can be safely ignored.

d: it's really 1 connection per server per second, which means it can get up to 12-15 per second. each server has it's own queue and logic, and we haven't tried to develop above that yet.

**Comment by leftdevel** [comment]
Sorry if I'm spamming. Just wanted to quickly ask (since I couldn't find any reference on the net):
My app requires to store an ID for webhook events (bounced, dropped). I was wondering what id should I prefer: if sg_event_id, or sg_message_id. Is there any meaningful difference between them? Can I query your API given one of these IDs?

For context, we are migrating away from Mandrill, and they provide an ID which we can use to later retrieve info about the failure thru their API.

Any comment will be much appreciated. Thanks.

**Comment by jacobmovingfwd** [comment]
`sg_event_id` will be unique to that *event*, and should be system unique. You can dedupe against it in the event you get double POSTs (rare, but can happen due to latency within SendGrid).

`sg_message_id` is unique the the *message*, and you should see multiple events per message.

You can't query our API either either of them. I would recommend storing both, as both are useful, but `sg_event_id` is your unique id if that's what you're looking for.

**Comment by leftdevel** [comment]
Thanks a lot!
