### ISSUE TITLE
Confusing indentation in api_table

### ISSUE THREAD

**Issue by rzats** [sendgrid/docs#2534]
In https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html#-Request-Body-Parameters and elsewhere, the difference between different depth levels is so small that it can be hard to tell whether a specific parameter is top-level or a member of a different parameter. Could be fixed by

- Simply [increasing the indentation](https://github.com/sendgrid/docs/blob/master/source/_assets/stylesheets/tables.less#L33-L52)
- Making objects/arrays collapsible
- Adding [grid lines](http://www.songho.ca/misc/treeview/files/treeview.png) to the table where appropriate

**Comment by ksigler7** [comment]
Hi @rzats, thanks for your suggestion! Right now, we're not actively improving that set of API docs because we're migrating over to a newer format. Here's that information in the new format: https://sendgrid.com/docs/API_Reference/api_v3.html. Let me know if you find the table to be confusing in this new format.
