### ISSUE TITLE
Troubleshooting Index

### ISSUE THREAD

**Issue by adminFS** [sendgrid/docs#2548]
https://sendgrid.com/docs/Classroom/Troubleshooting/index.html

I am a paying customer with Send Grid and have had an account for years. I have unable to login. So I reset my password and expect to receive an email. No email arrives. I again request to reset password and still no email arrives.

I am unable to contact support because I first have to login. Your website is barrier to working with customers instead of being a helpful tool.  Please have someone contact me at 775-445-9847 to unlock my account asap.

**Comment by ksigler7** [comment]
Hello @adminFS,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a docs specific issue, we would like to ask that you email our support team at support@sendgrid.com.

Thank you!

SendGrid DX Team
