### ISSUE TITLE
Account Sign Up FAQs

### ISSUE THREAD

**Issue by rehmke** [sendgrid/docs#2557]
Hello,

I received an interesting message upon signup for a free development email trial that stated that 'the algorithms' have deemed my application/registration as 'high-risk'.  Does this odd, unfortunate designation indicate that I will not be able to use SendGrid for my startup project?  Please advise, and thank you.

Best regards,

rehmke

Update: I received an email message from SendGrid 41 minutes after completing the sign-up process prompting me to confirm my email address, and upon doing so, I am sent to app.sendgrid.com, which is an inaccessible page (see attachment).  How to remedy?

<img width="1013" alt="screenshot" src="https://cloud.githubusercontent.com/assets/9312157/24107452/baabb392-0d58-11e7-8afe-2d2f3c1bf26d.png">

**Comment by kevin-work** [comment]
I also just got this. Any news?

**Comment by thinkingserious** [comment]
Hello @rehmke,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
