### ISSUE TITLE
Wrong template id responds with 201

### ISSUE THREAD

**Issue by thesmart** [sendgrid/docs#2616]
https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#-Template-Errors

I noticed that if we use a guide that is off by one character (change any character to a 0), the send API returns 201 and yet no email is queued according to the recent activity list.  This meant an hour was wasted trying to debug our email to realize that the template id was slightly off.

**Comment by ksigler7** [comment]
Hello @thesmart,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem.  This is actually the expected behavior of the API - the API itself doesn't do any of the character validations, that happens later in the process. If you're having any issues troubleshooting, please reach out to our support team at https://support.sendgrid.com.

Thank you!

SendGrid DX Team
