### ISSUE TITLE
Testing your connectivity to SendGrid's SMTP relay using Telnet

### ISSUE THREAD

**Issue by DarylMcCullough** [sendgrid/docs#2638]
https://sendgrid.com/docs/Classroom/Troubleshooting/Delivery_Issues/testing_your_connectivity_to_sendgrids_smtp_relay_using_telnet.html

I went through the steps and instead of getting "mail delivered" at the end, I got the message
250 Ok: queued as nhIMmON9SFOPcT0ii4nt2A

I don't know what that means, but the email never arrived.

Anyway, the troubleshooting should acknowledge the possibility of getting a "queued" message instead of "delivered".

**Comment by ksigler7** [comment]
Hi @DarylMcCullough,

250 Ok: queued is the success response (a mail never just sends, it gets queued on the ip that you're using). If a mail isn't delivered after this point, it is often an issue with the content (for example, most mail providers require that you have a from header in your content). The Suppressions section of app.sendgrid.com may provide some good troubleshooting information. If you're still having issues, please feel free to reach out to our support team: https://support.sendgrid.com.

Kaylyn

**Comment by thinkingserious** [comment]
Hello @DarylMcCullough,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
