### ISSUE TITLE
Account Under Review / Suspended

### ISSUE THREAD

**Issue by xiuwenzhao** [sendgrid/docs#2646]
Our account is sas@zxianstudio.com, this week it is suspended due to unknown reason!
We have tried a lot of ways, changing credit card, digging documents, emailing you.....

However we haven't got any response. Right now our account is suspended ! Our business is affected by this problem.
Please help us to resolve this problem.

ps1,
we have read this doc, but it didn't help. https://sendgrid.com/docs/Classroom/Troubleshooting/Account_Administration/account_under_review_suspended.html
ps2, 
we tried "contact" in a lot of ways, but there is no way to contact you.

**Comment by thinkingserious** [comment]
Hello @xiuwenzhao,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by rimvel** [comment]
> 
> 
> Hello @xiuwenzhao,
> 
> Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at https://support.sendgrid.com.
> 
> Thank you!
> 
> SendGrid DX Team

Same here. Service stopped, we've contacted support, but no answer for 4 hours.

**Comment by kaushikdevaraju** [comment]
Our account is support@spendwich.com, this account is showing Account Under Review, submitted to support team but no response please consider this one.
