### ISSUE TITLE
Recommended SMTP settings confusing steps

### ISSUE THREAD

**Issue by endersonmaia** [sendgrid/docs#2658]
https://sendgrid.com/docs/Classroom/Basics/Email_Infrastructure/recommended_smtp_settings.html

The first step says I need to use my `username` and `password,  and then the last step says I need to use the `apikey` for username and the api key for password.

Does that mean I can use one OR another ? I think it should be more clear, as the bullet lists made me think as steps to follow and configure.

**Comment by ksigler7** [comment]
Hi @endersonmaia,

Thanks for reaching out. The first bullet point is referring to your username and password that you use to log into app.sendgrid.com, and the last bullet is referring to the API Key that you create in bullet 2 (which you have to log into app.sendgrid.com in order to create). 

This page could definitely use some clarification though, and I've added it to our internal backlog!

Kaylyn
