### ISSUE TITLE
Question about opens

### ISSUE THREAD

**Issue by davemdub** [sendgrid/docs#2668]
Hi

I have a question about "opens".  I have a campaign where I send an email once per month to about 2000 addresses.  The email might go out on the 15th and then it will get clicks and opens for the next couple weeks until it tapers off.  Are the unique clicks and open specific to the entire campaign or the day?  Meaning, say on the 15th I send 2000 emails.  The category statistics reporting page shows that I sent 2000 emails and on the 15th got 200 unique opens.  For the next 2 weeks I get 600 more unique opens.  Is that 800 unique opens total or is there no way of knowing because the days are independent?

https://sendgrid.com/docs/Glossary/opens.html

**Comment by thinkingserious** [comment]
Hello @davemdub,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
