### ISSUE TITLE
Why is sendgrid.net “greylisted”?

### ISSUE THREAD

**Issue by lumineida** [sendgrid/docs#2682]
https://sendgrid.com/docs/Classroom/Deliver/Undeliverable_Email/why_is_sendgrid_net_greylisted.html

I am getting blocked on many emails with the error:

> 554 5.7.1 Service unavailable; Helo command [sendgrid.net] blocked using multi.uribl.com; Listed on grey

Is there anything I can do to help Sendgrid get out of the grey list?

Thanks!

**Comment by mikegreen** [comment]
File a support ticket and they can look at your send history/reputation and possibly move you to a better IP pool. 
I find it odd that support says it isn't impacting deliverability 
> Currently, there is no evidence of any actual impact on deliverability due to the greylisting

But clearly your email is being blocked... Is it being delivered later? Or terminally rejected?

**Comment by ksigler7** [comment]
Hello @lumineida ,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a docs specific issue, we would like to ask that you reach out to our support team at https://support.sendgrid.com.

Thank you!

SendGrid DX Team

**Comment by thinkingserious** [comment]
Hello @lumineida,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by thinkingserious** [comment]
Hello @lumineida,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by thinkingserious** [comment]
Hello @lumineida,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
