### ISSUE TITLE
Outdated content on "How to change the password for your SendGrid add-on via Azure"

### ISSUE THREAD

**Issue by Jehoel** [sendgrid/docs#2709]
Reopening Issue #1943 as per @thinkingserious's instructions because this is still an issue:

(I believe that auto-closing old issues is a very bad software engineering practice - bug reports are not the same thing as customer support tickets - the previous issue was only marked as old because it was not previously attended to - this is SendGrid's fault, not mine).

Original issue text below:

https://sendgrid.com/docs/Classroom/Troubleshooting/Account_Administration/how_to_change_the_password_for_your_sendgrid_add_on_via_azure.html

The Azure Portal does not list a "Reset password" option - only a "Change password" form which requires your current SendGrid password. There does not seem to be a way to actually reset a SendGrid password.

To clarify: this is a bug report I'm filing on GitHub because the bug is outdated/incorrect technical documentation, this is not a support request (so don't close this Issue unless it's fixed!)How to change the password for your SendGrid add-on via Azure

**Comment by ksigler7** [comment]
@Jehoel thanks so much for creating a new issue for this! I've added it to the docs backlog to update.

**Comment by vkolova** [comment]
Got this one!

**Comment by ksigler7** [comment]
thanks @vkolova!

**Comment by Jehoel** [comment]
I looked at the merged PR and the screenshot was not updated - the current Azure Portal looks very different.

I note that the "Reset password" option is now back in Azure, however clicking it redirects me to SendGrid's page asking me for a username - the Azure portal does not tell me what my username is.

Please reopen this issue.

**Comment by ksigler7** [comment]
thanks @Jehoel - for clarity, I've gone ahead and opened a new issue #3039

**Comment by ksigler7** [comment]
thanks for checking out the pull request @Jehoel 

@vkolova - do you mind updating with this latest information?

**Comment by ksigler7** [comment]
@Jehoel - your updated screenshot of how Azure takes you through to our general password reset page made me realize that all of these integration reset pages are out of date. This password reset process is something we implemented recently across the board to make our password reset process much more secure, and much less easy to hack. We just missed updating it with the integrations. Given this realization, I am going to close this here, because there is another open issue that is working on consolidating all of this information #2981, and I will incorporate this into that issue.

Thanks so much for the discussion and feedback on this! We don't always have easy access to our integrations and you've helped us to realize a pretty big issue!
