### ISSUE TITLE
I didn't receive the password reset email

### ISSUE THREAD

**Issue by balaoverture** [sendgrid/docs#2714]
I havent recieved email for my account overture_email. Please assist.

**Comment by ksigler7** [comment]
Hello @balaoverture,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. Often, this happens because you're trying to reset your password with an incorrect username (the UI doesn't tell you if it's wrong or not, it just says it sends an email). You can start the flow of verifying your username, and resetting your password with this form: https://support.sendgrid.com/hc/en-us/requests/new#forgot-username. Closing this issue, since it is not a docs specific issue.

Thank you!

SendGrid DX Team
