### ISSUE TITLE
End-to-end developer mode needed

### ISSUE THREAD

**Issue by bryan-kramer** [sendgrid/docs#2771]
It should be able to switch Sendgrid for a particular API key to a developer mode where emails reach sendgrid but are not sent to their to addresses, rather just to the developer's address.

The developer would like to see how changes to emails look without risking accidentally sending email out to real, other users.

**Comment by ksigler7** [comment]
@bryan-kramer thanks for your feedback! While you're in development, I would suggest updating your `to` parameter with your own email, instead of your customers emails to prevent something from accidentally going out where it shouldn't. If you have any other questions or issues while you're developing, you can contact our support at https://support.sendgrid.com!

**Comment by thinkingserious** [comment]
Hello @bryan-kramer,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
