### ISSUE TITLE
Lists and Segmentation

### ISSUE THREAD

**Issue by snoopspecial** [sendgrid/docs#2776]
https://sendgrid.com/docs/User_Guide/Marketing_Campaigns/lists.html

I've added contacts, but do not see the segment updating with the new contacts. How do I force an update manually? I've exported the segment and confirmed that it doesn't appear there.

**Comment by thinkingserious** [comment]
Hello @snoopspecial,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
