### ISSUE TITLE
BadRequest: CORS-Reason Python

### ISSUE THREAD

**Issue by jfajardo** [sendgrid/docs#2841]
Hi, i have this error, and no send a message
202

Server: nginx
Date: Tue, 15 Aug 2017 14:50:10 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 0
Connection: close
X-Message-Id: 5VAXXXX-GHSZROQ
Access-Control-Allow-Origin: https://sendgrid.api-docs.io
Access-Control-Allow-Methods: POST
Access-Control-Allow-Headers: Authorization, Content-Type, On-behalf-of, x-sg-elas-acl
Access-Control-Max-Age: 600
X-No-CORS-Reason: https://sendgrid.com/docs/Classroom/Basics/API/cors.html

```
# using SendGrid's Python Library
# https://github.com/sendgrid/sendgrid-python
import sendgrid
import os
from sendgrid.helpers.mail import *

sg = sendgrid.SendGridAPIClient(apikey='SG.XXXX')
from_email = Email("test@example.com")
to_email = Email("example@test.com")
subject = "Sending with SendGrid is Fun"
content = Content("text/html", "and easy to do anywhere, even with Python")
mail = Mail(from_email, subject, to_email, content)
response = sg.client.mail.send.post(request_body=mail.get())

print(response.status_code)
print(response.body)
print(response.headers)

```

**Comment by thinkingserious** [comment]
Hello @jfajardo,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
