### ISSUE TITLE
SMTP Ports

### ISSUE THREAD

**Issue by TestTalent** [sendgrid/docs#2859]
https://sendgrid.com/docs/Classroom/Basics/Email_Infrastructure/smtp_ports.html
Sendgrid send me a error: Connection to smtp.sendgrid.net:587 Timed Out, 404

**Comment by TestTalent** [comment]
Now the same mistake comes. After a while at the repeated reference there is a sending

**Comment by TestTalent** [comment]
![image](https://user-images.githubusercontent.com/16284873/30016954-ec7e676c-915f-11e7-990b-b6bfb93c584c.png)

**Comment by thinkingserious** [comment]
Hello @TestTalent,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
