### ISSUE TITLE
sg_event_id not present for *subscribe* event types

### ISSUE THREAD

**Issue by marcinzaremba** [sendgrid/docs#2862]
Event webhook documentation states:
```
We recommend that you use some form of deduplication when processing or storing your Event Webhook data using the sg_event_id as a differentiator, since this ID is unique for every event.
```
Reality is `sg_event_id` is sometimes (I also encountered cases where it is available) not available for event types: unsubscribe, group_unsubscribe, group_resubscribe, so this property cannot be used for differentiation.
However it is implicitly described in Parameter details section, where `sg_event_id` is not listed among "all the possible parameters".
It would be better to change "since this ID is unique for every event" to "since this ID is unique for every event where sg_event_id is present" when lack of this parameter in mentioned types of events is expected behavior.
If it is bug I would be grateful to report where needed to have it fixed.

What intermittent solution do you recommend for event deduplication for those types? Is `sg_message_id` unique enough for those?

**Comment by ksigler7** [comment]
Hello @marcinzaremba,

Thanks so much for your feedback! There are definitely some clarifications that can be made in the doc here. However, to get help with your question, I'd recommend that you file a ticket with our support team so that someone can look at your specific data. You can access support contact options by logging into https://support.sendgrid.com.

SendGrid Docs Team

**Comment by sayak119** [comment]
@ksigler7 can I work on this . Make required changes in event webhook doc

**Comment by ksigler7** [comment]
@sayak119 - sure, thanks!
