### ISSUE TITLE
My Account Has Been Suspended / Banned

### ISSUE THREAD

**Issue by hackzilla** [sendgrid/docs#2908]
I can't figure out how to "contact support"

This link describes the problem, but the only thing I can think to do is feedback, here, or "contact support", which redirects me back to searching support.

https://sendgrid.com/docs/Classroom/Troubleshooting/Account_Administration/account_under_review_suspended.html

**Comment by thinkingserious** [comment]
Hello @hackzilla,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by mrosa001** [comment]
Hi, my account has been suspended/ banned,
I would like to know how much I will pay for the last month, and the statistics sent in the last month,
in order to avoid this kind of problem in the future, I have been a client of sendgrid for more than 1 year,
and now I can not login or see my informations, the support is saying they can not help me,
I did not receive the email saying :  "your account is banned", 

I saw this in the sendgrid support :
"We don't make a habit of letting banned accounts back on, but if you would like to discuss it, please respond to the email you received regarding the ban."

I would like to review my account, thank you

mrosa001 is my account

**Comment by hackzilla** [comment]
@mrosa001 As I found out, you need to contact SendGrid directly.

**Comment by mrosa001** [comment]
I am trying to contact the sendgrid, but support is saying they can not
help,
I have to reply the banned email, but I dont receive the banned email.

We don't make a habit of letting banned accounts back on, but if you would
like to discuss it, *please respond to the email you received regarding the
ban.*

Support cannot assist in reactivation of banned accounts.

Em seg, 1 de abr de 2019 às 07:42, Daniel Platt <notifications@github.com>
escreveu:

**Comment by kendinho32** [comment]
My account is suspended, why?

**Comment by zz** [comment]
me too.  I don't known why. I upgrade with my card.  sendgrid is liaer totally.

**Comment by mishale22** [comment]
My account is suspended. What can I do?

**Comment by chwanyoung** [comment]
If you are an email marketing company, DO NOT use sendgrid!!!

their policy is too strict.

**Comment by usualwyy** [comment]
> If you are an email marketing company, DO NOT use sendgrid!!!
> 
> their policy is too strict.

I should have know this earlier.
I got banner at the next day after I paid.So stupid.

**Comment by ben2d2** [comment]
Why is my account suddenly banned? I did not receive an email about this. I can't log in to contact support. I tried creating a new account but that had some review process that I did not have to do when enabling through Heroku. Can someone advise?

**Comment by KyleRAnderson** [comment]
Can somebody help me, within the first hour of installing the Heroku Sendgrid add-on the account got banned - and I didn't even send a single message. I've had a support ticket open for well over a month with no reply.

**Comment by arathael** [comment]
They do ban your account if you do not immediately confirm your email address before closing the window. This happened to me into a heroku created account and got my email banned from creating further addons for my apps, just after confirming my domain and before even sending one single email. Contacting support is useless, I filed two tickets and they simply do not help. The answer is to create another heroku account and provison a new addon for Sendgrid. Oh I forgot to mention their Marketing Campaigns Add-on is just unavailable to install. I do think these guys here on github are making a good job with their lib, but the product lack of support and platform instability tags the company as amateur, at best.

**Comment by KyleRAnderson** [comment]
I just ended up going with Mailjet for email service instead, thanks for the insight though @arathael.

**Comment by yshmarov** [comment]
I was banned a few times and it's really frustrating. 

**Have to contact sendgrid support and after a while they unban me.** 

It's especially annoying that I can not open a support request from my account that was banned - only from a new account.
[![enter image description here][1]][1]


  [1]: https://i.stack.imgur.com/0doo6.png

**Comment by vitorbarros** [comment]
+1

**Comment by guilpejon** [comment]
I literally just installed the heroku addon and got banned as soon as I opened sendgrid. This is ridiculous.

**Comment by brjatoba92** [comment]
Me too. Now don't happy, my app need to be finalized  rsrs

**Comment by yshmarov** [comment]
Since Twilio acquired Sendgrid, many developers are experiencing the same issue:

https://www.reddit.com/r/rails/comments/jzi8oe/awful_send_grid_experience_looking_for_alternative/
https://github.com/themarshallproject/klaxon/issues/361
In my case, I am using SendGrid with Heroku

I managed to make it work by verifying a phone number at this link:

https://tools.heroku.support/addons-verification/verify

If it does not work for you, I would recommend to explore alternatives. Here is a good explanation of how to set up different SendGrid alternatives.

https://hixonrails.com/ruby-on-rails-tutorials/ruby-on-rails-action-mailer-configuration/

The easiest one (if you are using heroku) would be Mailgun. Yes sendgrid, I am unfortunately having to offer alternatives to YOU in YOUR own repo because you are not addressing a common issue in any way 👎

**Comment by ahanel13** [comment]
The same thing is happening to me. I was never even able to log into the SendGrid dashboard. Now when I try to re-add the add on is says my user has been banned.

**Comment by csenszike** [comment]
+1

I can log in for the first time (providing 2FA), and after the first minute it lockes me out. Unusable add-on this way. :(
Any work in progress on it?

**Comment by jNicker** [comment]
+1 same issue

**Comment by Malekradhouane** [comment]
+1 same on heroku

**Comment by stuart-clark** [comment]
One workaround is to create a Sendgrid account separately (not through Heroku Elements) and configure an API key via their web portal.

The blackhole here is you cannot contact support without an account, and Sendgrid banned the account. 

¯\_(ツ)_/¯

**Comment by alexfinnarn** [comment]
Boo SendGrid...boo to you. Now with 2FA required, I wonder how that plays into the SSO login via Heroku. Up till this point, a shared team account allowed us to log in. Now, I think we have to have individual seats? Boooo!!

**Comment by AhmedNadar** [comment]
I've ben banned.
Since 2017 and same error occur and Snedgrid didn't fix this issue. I don't know why it is closed..

I agree with @yshmarov and his [comment above](https://github.com/sendgrid/docs/issues/2908#issuecomment-732194727)  there are alternative and reliable services to sendgrid. 
He has a good post on using [Amazon SES](https://blog.corsego.com/send-emails-in-production-amazon-ses).

**Comment by Geozstevenzz** [comment]
I literally got banned at the sign up phase. Someone there has dreams of being a monopoly. Unfortunately for them they are not. So considering the complain trail above, I wont even bother opening an account only to get randomly banned later. Finding a better solution for my app.
