### ISSUE TITLE
How to change out your API Key

### ISSUE THREAD

**Issue by Whatthefoxsays** [sendgrid/docs#2985]
## To do:

Write a how-to section with the following content:

How to change your own code to have new API keys, so that you don't lose the ability to send. 

1. Generate new keys - don't invalidate the old ones 
2. replace old keys with new keys 
3. Test 
4. Invalidate your old keys 

Keep it short, concise, and put it on this page:

https://sendgrid.com/docs/User_Guide/Settings/api_keys.html#-API-Key-Permissions

**Comment by ksigler7** [comment]
@riktimmondal - you can create an API key here https://app.sendgrid.com/settings/api_keys

**Comment by NexWeb** [comment]
Dear @Whatthefoxsays,  

Are you referring to modifying your own code, using any particular language or SDK? 
The reason I ask is because that would vary depending on the SDK used and the text at: https://sendgrid.com/docs/User_Guide/Settings/api_keys.html#-API-Key-Permissions seems pretty clear about methods of creating, editing and deactivating keys.

**Comment by ksigler7** [comment]
Hey @NexWeb,
That's a really good point. I think what we're looking for here is actual steps. Right now, that page does include a lot of that information, but it should be reformatted into the steps for creating, editing, replacing, testing and deactivating API keys, rather than the wall of text it is currently. DOes that make more sense?

**Comment by NexWeb** [comment]
Thank you @ksigler7, for clearing that up.
