### ISSUE TITLE
Update the A/B testing page to have steps

### ISSUE THREAD

**Issue by ksigler7** [sendgrid/docs#3093]
https://sendgrid.com/docs/User_Guide/Marketing_Campaigns/a_b_testing.html

Currently, this page is just a block of text. It should be broken down into our jobs-to-be-done format titled A/B testing your campaign - each of the current sections could probably be steps, with information included from this FAQ: https://sendgrid.com/docs/Classroom/Build/Choose_Content/a_b_testing.html

There should be a table of contents at the beginning, and there should be a "Related Resources" section at the end.

Once you've incorporated the FAQ in, please delete the file, and redirect it to the User Guide file using redirects.htcaccess.

**Comment by duncanleung** [comment]
Hi @ksigler7 can I take this up?

My understanding of this issue is:

**Update the [/Marketing_Campaigns/a_b_testing](https://sendgrid.com/docs/User_Guide/Marketing_Campaigns/a_b_testing.html) page**

- Update title of the page to "A/B testing your campaign"
- Break down the steps into the "jobs-to-be-done" format
- Each of the current sections could possibly be steps
- Include information from the FAQ on information included from this FAQ: [/Classroom/Build/Choose_Content/a_b_testing](https://sendgrid.com/docs/Classroom/Build/Choose_Content/a_b_testing.html)
- Create a "table of contents" at the start of the page, linking to the different steps/subsections
- Create a "Related Resources" section with links at the end of the page
- Delete the old FAQ page [/Classroom/Build/Choose_Content/a_b_testing](https://sendgrid.com/docs/Classroom/Build/Choose_Content/a_b_testing.html), and redirect it to the [updated User Guide page](https://sendgrid.com/docs/User_Guide/Marketing_Campaigns/a_b_testing.html) using redirects.htcaccess

**Clarification Needed:**
One question - where can I find an example of the **jobs-to-be-done format**?

Is the format, on [User_Guide/Marketing_Campaigns/getting_started](https://sendgrid.com/docs/User_Guide/Marketing_Campaigns/getting_started.html) a correct format to follow?


Thanks for your help!

**Comment by duncanleung** [comment]
@ksigler7 I found a description of jobs-to-be-done format from another issue 3091

Jobs to be done style includes:
- Table of contents at the beginning
- "Additional Resources" section at the end
- Include sections to achieve the goal, with steps for each task (numbered steps, clear directions and correct UI workflow)


Maybe this 'jobs to be done format' should be written down on the main Readme / contribution guidelines to avoid having to repeat yourself =)

**Comment by ksigler7** [comment]
@duncanleung thanks for taking this up! The User_Guide/Marketing_Campaigns/getting_started is a perfect example for what to follow.

that is a great idea to add jobs-to-be-done information to the readme! There's another issue open right now to update the readme, I will add this in!
