### ISSUE TITLE
Remove Basic Auth from Docs

### ISSUE THREAD

**Issue by Whatthefoxsays** [sendgrid/docs#3122]
## To do:
Remove all instances of "Basic Auth" from the documentation. 

**Link to page**:

**Comment by kaysiz** [comment]
@Whatthefoxsays the To DO is missing link to page.

**Comment by ksigler7** [comment]
Hey @kaysiz, good question, here's some more detail: 

We now want all of our API Users to use an API Key to authenticate to their API instead of using Basic Authentication. There are still some remnants in the docs where we tell people to use Basic Authentication.

For example: In [this page](https://github.com/sendgrid/docs/blob/3fdfe03be5c80723abf14402b7746f049dbf955a/source/API_Reference/Web_API_v3/How_To_Use_The_Web_API_v3/authentication.md), you have the sentence "When authenticating using the on-behalf-of header, you will need to use the API key or basic auth credentials of the parent account." - now this should say only "you will need to use the API key credentials of the parent account."

I would tackle this problem by searching the repo for terms like "basic auth" and "basic authentication" to find places where sentences or steps may need to be updated.

**Comment by kaysiz** [comment]
@ksigler7 thank you for the clarity..let me give it a try.

**Comment by nicolasmdf** [comment]
Working on it!
