### ISSUE TITLE
Batch / Scheduled Send documentation is confusing

### ISSUE THREAD

**Issue by ry167** [sendgrid/docs#3269]
Just thought that I would point out that this article is quite confusing, not sure what the best fix would be

## Expected content

Title like "Scheduled Sends or "Batches" and information about Batches / Scheduled Sends, why and when they should be used

## Actual content

The page title is "Cancel Scheduled Sends" which is confusing. 

Then the article talks about creating and validating Batch sends.

**Link to page**: https://sendgrid.com/docs/API_Reference/Web_API_v3/cancel_schedule_send.html
and https://github.com/sendgrid/docs/blob/develop/source/API_Reference/Web_API_v3/cancel_schedule_send.apiblueprint

**Comment by ksigler7** [comment]
Hi @ry167,

Thanks so much for the suggestion! You're right that this seems odd. Right now, we are in the process of migrating all of our doc to our new format. So, this page is now here: https://sendgrid.api-docs.io/v3.0/cancel-scheduled-sends - it is odd there too.

I am going to close this pull request, because we're not really updating our old doc anymore since we are about to make the full switch, and our new docs format is not yet open source. However, thanks for noticing this, and thanks for bringing it to our attention! We are definitely looking into it internally.

SendGrid Docs team
