### ISSUE TITLE
Hacktoberfest Latinos !! Silux

### ISSUE THREAD

**Issue by gelvezz23** [sendgrid/docs#3298]
Lastimosamente no pude participar a tiempo ;( 
pero igual lo intento 

pertenesco a semillero de SILUX - Promoviendo el codigo libre ( FREE )

:v problema
vi que no hay casi latinos :( bueno hasta el momento no eh visto, casi todos los problemas se me hace dificil de identificar por la lengua en la que hablar( escriben), pero igual ahi hice lo que pude 

y lastima, en mi universidad eh estado muy atareado 

espero (y) que alguien diga algo :v:  :hacktoberfest

**Comment by ksigler7** [comment]
@gelvezz23 - thanks for your comment! This is a difficult one for this repo, because this repo is for our product documentation and our main documentation set is in English (you can check it out [here](https://sendgrid.com/docs/index.html) and we do not currently offer it in any other languages.

However, there are most definitely Latino contributors to our [code libraries](https://github.com/sendgrid)! In fact, one of our top contributors is from Brazil! You can see the SendGrid leaderboard [here](https://dx.sendgrid.com/hacktoberfest).

**Comment by gelvezz23** [comment]
@ksigler7 gracias :D

**Comment by gelvezz23** [comment]
@ksigler7 poco a poco voy aprendiendo sobre github
