### ISSUE TITLE
Transactional Templates: examples of sending with dynamic data

### ISSUE THREAD

**Issue by SimonEast** [sendgrid/docs#3323]
Looking at https://sendgrid.com/docs/API_Reference/Web_API_v3/Transactional_Templates/index.html

Can't seem to find an example of sending an email using a template stored on SendGrid. Would be nice if it could explain how to supply dynamic data, for example how to send an invoice using a stored template and passing in a data object containing line items, total, shipping cost etc. 

(Is that even possible with SendGrid currently?)

**Comment by ksigler7** [comment]
Hey @SimonEast - This is a question we get a lot! Check out our mail-send API documentation - https://sendgrid.api-docs.io/v3.0/mail-send - If you expand the properties in the Request data, you'll see an object for `template_id`, which is how you specify a transactional template, and then you'd use `sections` to have dynamic data. I hope that helps! If you are looking for help with your specific instance, you should reach out to our support team. You can access support contact options by logging into https://support.sendgrid.com.

I am going to close this issue because we are currently in the middle of an internal initiative to improve this doc (and the overall experience!) and I wouldn't want one of our contributors to duplicate our effort.

**Comment by SimonEast** [comment]
OK, sure. Thanks for the informative response. 😊

**Comment by ksigler7** [comment]
@SimonEast - We are actually looking for beta testers for our upcoming new transactional template functionality. Would you be interested in participating?

Some more info here: https://github.com/sendgrid/sendgrid-nodejs/issues/221

**Comment by SimonEast** [comment]
Ok good to know it's almost here, but unfortunately I'm not a SendGrid user (yet). Just researching possible options for an upcoming project. I don't think I'll be able to beta test at this stage.

**Comment by sendgrid-ryan** [comment]
Hey there! Quick update for this thread––

### Dynamic content for Transactional Templates is here!
This morning, our team publicly launched dynamic content for transactional templates. It is now available for all customers sending over v3 of our Mail Send API. Iterate over lists, handle conditionals and more, thanks to native support for a subset of Handlebars syntax!

More information can be found in our [blog post announcement](https://sendgrid.com/blog/how-to-use-sendgrids-dynamic-templates-for-your-transactional-emails/).

**Documentation:** 
 
 - [How to Send an Email With Dynamic Transactional
   Templates](https://sendgrid.com/docs/User_Guide/Transactional_Templates/how_to_send_an_email_with_transactional_templates.html)
 - [Using Handlebars](https://sendgrid.com/docs/User_Guide/Transactional_Templates/Using_handlebars.html)
 - [API Docs](https://dynamic-templates.api-docs.io/3.0/mail-send-with-dynamic-transactional-templates/v3-mail-send)

**Comment by camslice** [comment]
FYI this is currently being implemented here https://github.com/sendgrid/sendgrid-php/issues/648

**Comment by Joshandrews43** [comment]
None of the examples linked to above demonstrate how to send two emails to two different people with different data (e.g. different `dyanmic_template_data` fields). If someone could provide a code example I would appreciate it.

**Comment by sendgrid-ryan** [comment]
Hey @Joshandrews43! Thanks for the question. We have a few examples of some templates/use cases available (complete with test JSON data) here: https://github.com/sendgrid/email-templates/tree/master/dynamic-templates

Let me know if that doesn't help out! We're here for ya.
