### ISSUE TITLE
Click tracking links with links containing href parameters

### ISSUE THREAD

**Issue by c3mohamn** [sendgrid/docs#3416]
https://sendgrid.com/docs/Classroom/Track/Clicks/click_tracking_links_have_stopped_working.html

Problem
------------------------
If a link has an href param, your generated click tracking link replaces the href param link, rather than the whole link containing that href param.

Example
------------------------
https://www.facebook.com/dialog/share?app_id=966242223397117&href=http://google.ca/

Turns in to:
https://www.facebook.com/dialog/share?app_id=966242223397117&href=[click tracking link]

Which gives an error when following the link in the email.

------------------------

A temp solution would be to make the href param link not follow the guildelines (https://sendgrid.com/docs/Classroom/Track/Clicks/click_tracking_html_best_practices.html).

So instead of using http://google.ca/ 
I did www.google.ca/

**Comment by ksigler7** [comment]
Hey @c3mohamn, 

Thanks for the feedback, and thanks for the workaround! I've passed the information about this bug onto the team. They may reach out to you if they have any questions. For now, I am going to close this issue, since it's not a specific bug about our docs, but thanks again for the info!

SendGrid Docs team
