### ISSUE TITLE
Subject line in sendgrid mail shows copyright characters as &copy; similar for &trade etc

### ISSUE THREAD

**Issue by vivek-vas** [sendgrid/docs#3514]
https://sendgrid.com/docs/Classroom/Basics/Misc/support.html

**Comment by thinkingserious** [comment]
Hello @vivek-vas,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
