### ISSUE TITLE
How to change my password by the webinterface. 

### ISSUE THREAD

**Issue by peterdew** [sendgrid/docs#3527]
My password can't be changed. The Edit-button behind the username-password section in the account-details screen is disabled. Why?

**Comment by thinkingserious** [comment]
Hello @peterdew,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
