### ISSUE TITLE
Laravel example is not working correctly

### ISSUE THREAD

**Issue by eichgi** [sendgrid/docs#3559]
I am implementing sendgrid with Laravel so I leverage from your example, but so far I had to make 2 fixes for making it work:

In file `app/Mail/TestEmail.php`

**1. How to access data**
You cannot access to `->with([ 'message' => $data['message'] ]);` from inside build() because it's a public attribute so it should be changed to `->with(['message' => $this->data['message']]);`

**2. You cannot use the key "message" along _with_ method**
In somehow Laravel defines "message" key as a object when is received in the view. In the same line as point 1 I had to change `->with(['message' => $this->data['message']]);` for `->with(['greeting' => $this->data['message']]);`.

So I could finally display the value on my view like it:
```
<!DOCTYPE html>
<html lang="en-US">
<head>
    <meta charset="utf-8">
</head>
<body>
<h2>{{$greeting}}</h2>
<p></p>
</body>
</html>
```

https://sendgrid.com/docs/Integrate/Frameworks/laravel.html

Tested on Laravel 5.6
Greetings!

**Comment by ksigler7** [comment]
Greetings @eichgi! Thanks for letting us know about the fixes you made! This is awesome. Would you be willing to make a pull request on those docs pages with your fixes?

**Comment by eichgi** [comment]
Yes, I will make a PR with the fixe. Glad to help!

**Comment by ksigler7** [comment]
thanks to @cferrante, the first half of this issue has been fixed!

**Comment by remyapv** [comment]
@ksigler7 

Did some debugging here:

**What went wrong:**
To send a new message using the view, Laravel uses this method  Illuminate\Mail\Mailer:: send

The message is being created and assigned to an array with key **message**. If we use the same variable to assign data to the template, then this get replaced with an instance of **Illuminate\Mail\Message** and rendering the template will cause an error as an object is received in the view

`$data['message'] = $message = $this->createMessage();`


As @eichgi mentioned this can be fixed by renaming the variable. I could raise a PR for this.
