### ISSUE TITLE
Documentation about substitutions in Personalizations

### ISSUE THREAD

**Issue by b0rgbart3** [sendgrid/docs#3582]
https://sendgrid.com/docs/Classroom/Send/v3_Mail_Send/personalizations.html

This article explains how to include a personalizations array when sending email with SendGrid -- but it doesn't explain HOW to use substitutions -- Is this a known convention that I'm unaware of?  I don't understand HOW the subsitutions will work -- In this example:
```
"%fname%": "recipient",
 "%CustomerID%": "CUSTOMER ID GOES HERE"
```

Where is **fname** coming from?  Is that an array of my customer names?  What are the **%** characters for?  Again -- is this a convention I'm unaware of?  Can we see an example with real arrays -- to better see how this would be applied?

**Comment by thinkingserious** [comment]
Hello @b0rgbart3,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by ksigler7** [comment]
@b0rgbart3 thanks for this feedback! we are actually currently in the process of improving this doc. In the meantime, our awesome support team should be able to help you!
