### ISSUE TITLE
Email Activity Feed

### ISSUE THREAD

**Issue by AELSchauer** [sendgrid/docs#3594]
https://sendgrid.com/docs/User_Guide/email_activity_feed.html

Provide information on how to view unique arguments in the Activity Feed. The documentation for the unique arguments says to go to the Activity Feed, but I can't find them.

**Comment by thinkingserious** [comment]
Hello @AELSchauer,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by Whatthefoxsays** [comment]
@AELSchauer Thanks for your feedback. Tracking Unique arguments is not a feature in the new Email Activity Feed. For figuring out a workaround, please get in touch with our support team.
