### ISSUE TITLE
sendgrid

### ISSUE THREAD

**Issue by ananddayama** [sendgrid/docs#3605]
https://sendgrid.com/docs/Integrate/Mail_Clients/outlook.html

**Comment by thinkingserious** [comment]
Hello @ananddayama,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
