### ISSUE TITLE
How do I whitelist emails to keep them from dropping?

### ISSUE THREAD

**Issue by randyFRS** [sendgrid/docs#3676]
https://sendgrid.com/docs/Classroom/Deliver/Undeliverable_Email/how_do_i_keep_emails_from_dropping.html

Feature doesn't actually work. We've got one domain in particular that continues to get bounced/blocked even though it's listed in our Address Whitelist area.

Sorry, the link on https://github.com/sendgrid/docs/blob/develop/CONTRIBUTING.md for the bug report template is dead. https://github.com/sendgrid/docs/.github/ISSUE_TEMPLATE

**Comment by ksigler7** [comment]
@randyFRS - thanks for the info on the bug report template being bad.

In terms of your issue, please file a ticket with our awesome support team, they are much better equipped to help troubleshoot this sort of individual issue! You can access support contact options by logging into https://support.sendgrid.com.

Closing this since I already opened a PR for the contributing.md issue and this otherwise isn't a docs specific issue.

**Comment by thinkingserious** [comment]
Hello @randyFRS,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by randyFRS** [comment]
Thanks. You might also want to fix the way your documentation routes people.
