### ISSUE TITLE
Activity Feed - Feedback

### ISSUE THREAD

**Issue by jamalnasir** [sendgrid/docs#3712]
Suppose, I send millions of emails (not using campaigns). And I want to filter only the delivered on the activity feed. Which currently this feature is not there. 

That would be better if users are provided with the events filters.

**Comment by ksigler7** [comment]
hi @jamalnasir - there is a drop-down on the top right of the Email Activity screen that provides specific event filters.

If you have other questions or feature requests, please contact our awesome support team. You can access support contact options by logging into https://support.sendgrid.com.

I am closing this since it is not a docs specific issue.

SendGrid Docs Team
