### ISSUE TITLE
Error sending email with attachment - PHP

### ISSUE THREAD

**Issue by ronaldo2018** [sendgrid/docs#3723]
The email is sending normally, however the original image does not arrive, a new file arrives with the name of the image and with the extension of the image, opening this file with the extension of the image displays this:
"@images/fotoMonteCaixa/15316973195b4bd8a79d610.png"

And sending the email on the screen displays:
Array ( [api_user] => usuario[api_key] => senha  [to] => usuario@dominio.com [subject] => test of file sends [html] =>
the HTML

[text] => the plain text [from] => contato@dominio.com.br [files[15316973195b4bd8a79d610.png]] => @images/fotoMonteCaixa/15316973195b4bd8a79d610.png ) {"message":"success"}

I am using the code below for the submissions:

https://sendgrid.com/docs/Integrate/Code_Examples/v2_Mail/php.html

**Comment by thinkingserious** [comment]
Hello @ronaldo2018,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
