### ISSUE TITLE
Missing X-Message-ID from Header v3

### ISSUE THREAD

**Issue by soccerwiz13** [sendgrid/docs#3855]
When we send email using the V3 end point in sendgrid C# library, we do not get the message ID in the reponse. Our header looks like this:

Connection: keep-alive
Access-Control-Allow-Origin: https://sendgrid.api-docs.io
Access-Control-Allow-Methods: POST
Access-Control-Allow-Headers: Authorization, Content-Type, On-behalf-of, x-sg-elas-acl
Access-Control-Max-Age: 600
X-No-CORS-Reason: https://sendgrid.com/docs/Classroom/Basics/API/cors.html
Date: Fri, 17 Aug 2018 17:03:26 GMT
Server: nginx

The documentation states there should be an X-Messsage-ID in the header. What are we missing?

**Comment by thinkingserious** [comment]
Hello @soccerwiz13,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
