### ISSUE TITLE
Error (Unauthorized )trying to use SendGrid marketing

### ISSUE THREAD

**Issue by Compunick** [sendgrid/docs#3889]
I have a BRONZE tier sendgrid account.  Logged into SendGrid,  every time I navigate to the Marketing section,  it gives me a "/ui/error/401/"  page 'Unauthorized'  --- Why is that?

## Actual content

**Link to page**:

**Comment by thinkingserious** [comment]
Hello @Compunick,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
