### ISSUE TITLE
CCed Address not getting bulk emails

### ISSUE THREAD

**Issue by avdhoota** [sendgrid/docs#3904]
Hi team,

I am using sendgrid to send emails in Bulk. 
For ex. I am sending an email to 100 users with 10 substitutions in a personalization object. So i am addind 100 personalization to sendgrid mail object. So with each personalization object i'm adding CC email id. 

Now users who are in To, getting the email properly, but the user who is CCed, gets only one email. Here my requirement is like if i am sending 100 emails to different users, i should get 100 emails too if my email id is in CC.

Kindly let me know the solution for the same.

**Comment by thinkingserious** [comment]
Hello @avdhoota,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
