### ISSUE TITLE
Email content not preview.

### ISSUE THREAD

**Issue by mbbhimani** [sendgrid/docs#3914]
How can i check what email goes to my customers ?? there are no option for view content of send mails.

**Comment by thinkingserious** [comment]
Hello @mbbhimani,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
