### ISSUE TITLE
download attacvhment

### ISSUE THREAD

**Issue by andyg2** [sendgrid/docs#3916]
I'm using SendGrid Parse however I have not been able to find where to access attachments sent.
In the `attachment-info` posted to my API I can see the attachment data but as yet I haven't discovered how to access the attachment files.
Any help appreciated.

```

	attachment1:  {
		"filename": "20180406T073501Z - 001.zip",
		"name": "20180406T073501Z - 001.zip",
		"type": "application / octet - stream",
		"content - id": "f_jldkrz450"
	},

```

**Comment by andyg2** [comment]
I'm using SendGrid Parse however I have not been able to find where to access attachments sent.
In the `attachment-info` posted to my API I can see the attachment data but as yet I haven't discovered how to access the attachment files.
Any help appreciated.

```

	attachment1:  {
		"filename": "20180406T073501Z - 001.zip",
		"name": "20180406T073501Z - 001.zip",
		"type": "application / octet - stream",
		"content - id": "f_jldkrz450"
	},

```

**Comment by thinkingserious** [comment]
Hello @andyg2,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
