### ISSUE TITLE
I cannot login into my free account anymore

### ISSUE THREAD

**Issue by bobseiclair** [sendgrid/docs#3930]
I create a free trial account to which my access is denied despite my password renewal twice..

account1
username: bobseinclair
password: tomi@2018

account2
uesrname: bernadin
password: serikp@10

thanks

## Actual content

**Link to page**:

**Comment by thinkingserious** [comment]
Hello @bobseiclair,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
