### ISSUE TITLE
Blacklisted Server

### ISSUE THREAD

**Issue by MadSpaniard** [sendgrid/docs#3939]
I have an account (shared) with SendGrid, and discovered that the server my account was assigned to has been blacklisted.  It was blacklisted by no fault of our own - in fact, we have not sent any emails out as of yet on our SendGrid acocunt.  There must be another SendGrid customer on that same account causing the blacklisting.

So, I put in a ticket to support, they said they would reach out to de-list the server.  That was 1 month ago, and the server (167.89.100.239) remains blacklisted as seen here:

https://mxtoolbox.com/SuperTool.aspx?action=blacklist%3a167.89.100.239&run=toolpage

SendGrid says they cannot change my acocunt to a different server.  Meanwhile, server is still blacklisted and therefore unusable for marketing campaigns to my target list (customer emails at major corporations).

Is there any way to solve the blacklisting on server 167.89.100.239?

## Actual content

**Link to page**:

**Comment by micgid** [comment]
Same here for:

The hotmail.com server blocked this message from being delivered. While we won't try to send this message again, we will attempt to send new messages to this address in the future. 

You can view all addresses in your Blocks suppression group. Learn more.

Full response from the hotmail.com server:

550 5.7.1 Unfortunately, messages from [167.89.106.6] weren't sent. Please contact your Internet service provider since part of their network is on our block list (S3140). You can also refer your provider to http://mail.live.com/mail/troubleshooting.aspx#errors. [SN1NAM04FT035.eop-NAM04.prod.protection.outlook.com]

How could we remove this from blacklist ?

**Comment by ksigler7** [comment]
Hey @micgid and @MadSpaniard - we have some really good information about blacklists here - https://sendgrid.com/docs/glossary/blacklists/. If that's not helpful, please reach out to our awesome Support Team - they're in a much better place to help you with individual blacklists. You can access support contact options by logging into https://support.sendgrid.com. 

I'm going to close this issue since it's not a problem with the docs repo.

SendGrid Docs Team
