### ISSUE TITLE
Failed to upgrade billing

### ISSUE THREAD

**Issue by rahmatoktavian** [sendgrid/docs#3945]
Hi Sendgrid Team,

I am trying to upgrade account billing from free to essential (40K email/month).
after fiiled up the billing information form, there's message : GatewayTransactionError  (please see attachment)
![error sendgrid](https://user-images.githubusercontent.com/43527551/45935068-56323080-bfd1-11e8-88d6-bc5be18e6e4a.png)

Please help me because i need to upgrade account soon.
Note : my credit card is still available 

Regards,
Rahmat

**Comment by thinkingserious** [comment]
Hello @rahmatoktavian,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
