### ISSUE TITLE
SMTP Relay | Authentication failed

### ISSUE THREAD

**Issue by floragroup** [sendgrid/docs#3947]
Hello,

 I already make everything is done but I face problem when I send the mail from smtp relay for our mail server (Kerio connect) as below log from our server for test email ..

<a******i@gmail.com>, Result: delayed, Status: 5.7.0 535 Authentication failed: The provided authorization grant is invalid, expired, or revoked, Remote-Host: smtp.sendgrid.net, Msg-Id: 04b901d45488$e52f6140$af8e23c0$@floragroup.net

I don’t know where the wrong I already try everything and reconfigure my DNS and CNAME and take verified but when I send email got that error.

We looking for help from your side ASAP.

BR,

**Comment by ksigler7** [comment]
Hello @floragroup,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a docs specific issue, we would like to ask that you reach out to our support team at https://support.sendgrid.com.

Thank you!

SendGrid DX Team
