### ISSUE TITLE
problem in monthly payment

### ISSUE THREAD

**Issue by Alvaropague** [sendgrid/docs#3992]
Hello, I can not afford the card. It is giving problem of diaper. What do I need to do to pay the bill? The card is ok and I use it daily.

**Comment by Alvaropague** [comment]
Você quis dizer Precisamos de uma solução emergencial para não travar nossa plataforma.
We need an emergency solution to not stop our platform.

**Comment by thinkingserious** [comment]
Hello @Alvaropague,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by Alvaropague** [comment]
I can not pass any credit cards.


Do I need to change something in the configuration?
this panel https://support.sendgrid.com does not have the information to solve my problem.
I really need your help to find out what's making it difficult.
