### ISSUE TITLE
Your login was unsuccessful

### ISSUE THREAD

**Issue by tenharenda** [sendgrid/docs#4054]
## Actual content

**Link to page**:
![image](https://user-images.githubusercontent.com/43896541/46564680-4115a580-c8df-11e8-8cde-c66a2dc09619.png)
![erro](https://user-images.githubusercontent.com/43896541/46564690-64d8eb80-c8df-11e8-84df-ada58a1889ef.png)

**Comment by thinkingserious** [comment]
Hello @tenharenda,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
