### ISSUE TITLE
AOC

### ISSUE THREAD

**Issue by Superkrowka** [sendgrid/docs#4104]
Hi, we need a pci compliant email provider - can you please provide your pci aoc.

**Comment by thinkingserious** [comment]
Hello @Superkrowka,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
