### ISSUE TITLE
How to create list in sendgrid

### ISSUE THREAD

**Issue by VirendraArekar** [sendgrid/docs#4167]
> I tried to create list but unable to create it and how to pass contacts to that list with php help me.

**Comment by thinkingserious** [comment]
Hello @VirendraArekar,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
