### ISSUE TITLE
Pixel Tracking Description Link 404

### ISSUE THREAD

**Issue by luciajimenez** [sendgrid/docs#4300]
## Expected content
"Web API" hyperlink under Open Tracking section directs to a 404. 

## Actual content

**Link to page**: https://github.com/sendgrid/docs/blob/develop/content/docs/ui/account-and-settings/tracking.md

**Comment by luciajimenez** [comment]
Taking care of this one ^

**Comment by dagolinuxoid** [comment]
@ksigler7 That's interesting - actually a source code which includes `[v3 Web API]({{root_url}}/API_Reference/Web_API_v3/index.html)` on github represents a valid link https://sendgrid.com/docs/API_Reference/Web_API_v3/index.html. The problem is - even though the source code is correct, on production site a link which represents **v3 WEB IPA** has different url https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/Index/ and will send you to 404. How can it be? It should be index.html instead of Mail/Index/
