### ISSUE TITLE
Resending Confirmation Email Not possible

### ISSUE THREAD

**Issue by buttflattery** [sendgrid/docs#4563]
In the docs it is mentioned that to verify your email you should go to the link https://app.sendgrid.com/guide whereas this link requires the user to login first and i cant login as i didnt received a signup email after registring.

## Expected content
I expect the link should open without the user to require login

## Actual content
It asks an unconfirmed user to login first who cant

**Link to page**: https://sendgrid.com/docs/ui/account-and-settings/verifying-your-account/

**Comment by thinkingserious** [comment]
Hello @buttflattery,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
