### ISSUE TITLE
Cannot update billing

### ISSUE THREAD

**Issue by tychovbh** [sendgrid/docs#4678]
I'm trying to update my billing information, but i receive an error: Invalid reason ..... 
There is not input field or input selector where I can give a reason so it is impossible for me to update my billing information 
## Expected content
That i can change my billing information

## Actual content
<img width="729" alt="screen shot 2018-10-31 at 10 16 49" src="https://user-images.githubusercontent.com/5880561/47798348-f6812080-dd06-11e8-9005-d6c620169b41.png">

**Comment by thinkingserious** [comment]
Hello @tychovbh,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
