### ISSUE TITLE
Cancel my account 

### ISSUE THREAD

**Issue by norapyk** [sendgrid/docs#4715]
(https://support.sendgrid.com).
You can contact SendGrid support from the [SendGrid Support Portal](I am out of town and

If you're reporting an issue with our docs, thanks for letting us know!
-->

## Actual content

**Link to page**:

**Comment by norapyk** [comment]
Only on my phone and finding it difficult to cancel my account.  Went to billing and only found contact customer servuce.  Please refund the amount charged on my credit card

**Comment by thinkingserious** [comment]
Hello @norapyk,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by norapyk** [comment]
This is NOT a github issue.  Want to cancel our subbscripotion and very surprised Sendgrid makes this difficult


On Nov 2, 2018, at 11:41 AM, Elmer Thomas <notifications@github.com> wrote:

Hello @norapyk <https://github.com/norapyk>,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at  <https://support.sendgrid.com/>https://support.sendgrid.com <https://support.sendgrid.com/>.

Thank you!

SendGrid DX Team
