### ISSUE TITLE
sendgrid Login is not working

### ISSUE THREAD

**Issue by ujjawal2005** [sendgrid/docs#4721]
My Login is not working. Can you please check and resolve this urgently.
My user id is : ujjawal2005
email: ujjawal.abhinav@gmail.com

Thanks,
Uj

**Comment by thinkingserious** [comment]
Hello @ujjawal2005,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by Umer-klab** [comment]
Hello !!
Please check i'm recently create account in sendgrid and its not working while i'm sending confirmation email and its not sending email to confirm my account.
USERNAME: jojo101
Email: umer@muneektech.com
Please fix this ASAP tons of work is pending.
Thankyou !!
