### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by jenramella** [sendgrid/docs#4723]
## Actual content

**Link to page**:

**Comment by jenramella** [comment]
I am having trouble logging in using what I thought was my password. The forgot password option never sent an email to my/our account. Account is Boston Interiors - bostoninteriorsdigital@gmail.com

Thank you,
Jen

**Comment by ksigler7** [comment]
Hello @jenramella ,

We're sorry you are having this problem! Usually, if the forgot password option isn't emailing you, it's because you are using the incorrect username. Our awesome support team can help you get this worked out - please contact them through this form: https://support.sendgrid.com/hc/en-us/requests/new#forgot-username

SendGrid Docs Team
