### ISSUE TITLE
How do I attach log files to cURL calls?

### ISSUE THREAD

**Issue by ddengster** [sendgrid/docs#4741]
As per title. Keep in mind that I need to append the contents of the file to the json's "content" tag.

**Comment by thinkingserious** [comment]
Hello @ddengster,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
