### ISSUE TITLE
asm_group_id not working with cURL based email

### ISSUE THREAD

**Issue by mark-ellul** [sendgrid/docs#4746]
curl --request POST \
  --url https://api.sendgrid.com/v3/mail/send \
  --header 'Authorization: Bearer YOUR_API_KEY' \
  --header 'Content-Type: application/json' \
  --data '{"personalizations": [{"to": [{"email": "recipient@example.com"}]}],"from": {"email": "sendeexampexample@example.com"},"subject": "Hello, World!","content": [{"type": "text/plain", "value": "Heya!"}], "asm_group_id": ASM_GROUP_ID}'

## Expected content
Should send the email with the "Email Preferences" Link and Unsubscribe Link should only unsubscribe to the group

## Actual content
Unsubscribe link is added but once clicking on the unsubscribe link, the email address is added to the Global suppressions list.

**Link to page**:
https://sendgrid.com/docs/for-developers/sending-email/curl-examples/#hello-world

**Comment by thinkingserious** [comment]
Hello @mark-ellul,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
