### ISSUE TITLE
Limit 2 per Azure Subscription

### ISSUE THREAD

**Issue by xyz92** [sendgrid/docs#4749]
I was going through the documentation https://sendgrid.com/docs/for-developers/partners/microsoft-azure/ and it says 'You are limited to 2 SendGrid accounts per Azure subscription'. I'm trying create SendGrid Account with ARM Template for multiple environments (more than 2) within a subscription. Is there an alternate way to do this because of this limit? Thank you!

**Comment by thinkingserious** [comment]
Hello @xyz92,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by xyz92** [comment]
@thinkingserious I reached out to the support team and the team mentioned they do not have great insight on this as Azure is an authorized reseller of SendGrid and they keep all of their billing, upgrades/downgrades, account creation and handling separate from SendGrid.

**Comment by kumammanish** [comment]
This still is an issue and I am too facing this. I do not know why this thread was closed.
