### ISSUE TITLE
attach pdf in email using curl 

### ISSUE THREAD

**Issue by vaishnavhiren1993** [sendgrid/docs#4755]
i want to send email with pdf attachment using html form upload file 
how can i attach file .
i am using .
$file_name = $_FILES['photo']['name'];
$tmp_name = $_FILES["photo"]["tmp_name"];
$file_type = $_FILES["photo"]["type"];
$file_size = $_FILES["photo"]["size"];

$documentList = array(
 $file_name => "@" . realpath($file_name)
);
if(count($documentList)>0){
foreach($documentList as $fileName=>$documentPath){
$params['files['.$fileName.']'] =  $documentPath;
}}
i got email and attachment but file size was 1 kb and it's broken.
i try this as well 
$cfile = curl_file_create($file_name,$file_type,$tmp_name);
$params = array ( 'files' => '$file_name')
same result

**Comment by thinkingserious** [comment]
Hello @vaishnavhiren1993,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
