### ISSUE TITLE
Zapier and Sengrid documentation discrepancy

### ISSUE THREAD

**Issue by andrewmiller1** [sendgrid/docs#4758]
## Zapier

https://zapier.com/help/how-get-started-sendgrid/

Pro and up, and use https://app.sendgrid.com/settings/teammates

## Sendgrid

https://sendgrid.com/docs/for-developers/sending-email/zapier-sending-from-google-sheet-rows/

Bronze and up, and use https://sendgrid.com/credentials

**Link to page**: https://github.com/sendgrid/docs/blob/master/content/docs/for-developers/sending-email/zapier-sending-from-google-sheet-rows.md

Which one is to be followed?

**Comment by thinkingserious** [comment]
Hello @andrewmiller1,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
