### ISSUE TITLE
Problem in getting email marketing campain templates

### ISSUE THREAD

**Issue by adeel3612** [sendgrid/docs#4762]
I am unable to get the email marketing campaigns templates. Is there any api provided for this. Only templates which i can get are the transactional templates but i cannot use them in campaigns. 

Any kind of help would be much appreciated.

**Comment by thinkingserious** [comment]
Hello @adeel3612,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
