### ISSUE TITLE
Hi guys, we need more than 2 paid Sendgrid accounts per Azure subscription

### ISSUE THREAD

**Issue by marina-mil** [sendgrid/docs#4764]
How do I enable/increase limit on Azure Subscription for more than 2 paid Sendgrid accounts.
The limit should be lifted for paid accounts.

thanks

Marina

**Comment by xyz92** [comment]
I have the same question.

**Comment by thinkingserious** [comment]
Hello @marina-mil,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
