### ISSUE TITLE
Unable to use Substitution Tags in image source fields

### ISSUE THREAD

**Issue by januwland** [sendgrid/docs#4778]
Wasn't sure where else to put this, trying to run a google-sheets powered loot store entirely through email campaigns, need to match images with voucher details, links, and text - all of which are attached to purchaser ids and randomised with an rng - I can't think of another way to populate the correct images.

https://sendgrid.com/docs/API_Reference/SMTP_API/substitution_tags.html

<img width="1502" alt="screenshot 2018-12-05 18 53 01" src="https://user-images.githubusercontent.com/38091842/49498428-264fb500-f8bf-11e8-9c6b-b796667836c9.png">
<img width="787" alt="screenshot 2018-12-05 18 54 03" src="https://user-images.githubusercontent.com/38091842/49498429-264fb500-f8bf-11e8-95a9-7999e2494551.png">

**Comment by thinkingserious** [comment]
Hello @januwland,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
