### ISSUE TITLE
Locked out of account

### ISSUE THREAD

**Issue by Eleventco** [sendgrid/docs#4780]
We are locked out of our account and cannot access it, reset the password or access the support site.

## Actual content

**Link to page**:

**Comment by thinkingserious** [comment]
Hello @Eleventco,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
