### ISSUE TITLE
How do I chat with support?

### ISSUE THREAD

**Issue by srednasoft** [sendgrid/docs#4781]
Hi,

I can't find the chat function to support

please help.

Brgs 
Anders Rinvoll
Statnett SF

**Comment by thinkingserious** [comment]
Hello @srednasoft,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
