### ISSUE TITLE
ERROR: Use of const in strict mode node v0.12.0  is not supporting

### ISSUE THREAD

**Issue by sagarsutar** [sendgrid/docs#4783]
Hi Team,
we have developd applicaion i nodejs  node v0.12.0
  and  const is not supporting 
const {Client} = require('@sendgrid/client');
^^^^^
Use of const in strict mode.  

Could you please suggest how to modify this 

## Actual content

**Link to page**:

**Comment by thinkingserious** [comment]
Hello @sagarsutar,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
