### ISSUE TITLE
Trouble with click tracking when ' symbol in href

### ISSUE THREAD

**Issue by nenazhenkoa74** [sendgrid/docs#4787]
### Problem
If a link has a ' symbol, your generated click tracking link trimmed after it.
### Example
www.example.com/docs/doc'dec2018.xlsx
becomes
www.example.com/docs/doc

**Comment by thinkingserious** [comment]
Hello @nenazhenkoa74,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
