### ISSUE TITLE
OH MY GOD!!!  PLEASE SOMEBODY CONTACT US - THIS IS RIDICULOUS

### ISSUE THREAD

**Issue by parman55** [sendgrid/docs#4789]
WE HAVE BEEN TRYING TO GET OUR BALANCE PAID FOR OVER A WEEK.  WE CAN'T FIND A PHONE NUMBER TO CALL YOU - UNBELIEVABLE..... I CAN'T LOGIN TO MY ACCOUNT..... I HAVE ASKED FOR A PASSWORD RESET AND HAVEN'Y HAD ANY REPLY FOR 3 HOURS.

WHAT'S GOING ON???  WE ARE NOT HAPPY.  I HAVE THINGS THAT NEED TO BE SENT VIA THE LIST SERVER AND I CAN'T GET IT DONE.

MY ACCOUNT NAME IS JEFFREY.SISK@NAVY.MIL..... MY PURCHASER IS JAMIE MCGEE.  PLEASE CALL HER AT 757-444-3520  X7030 IMMEDIATLEY.

CURRENT TICKET NUMBER FROM LAST WEEK IS  #1720671 

THANKS.

**Comment by ksigler7** [comment]
Hello @parman55 ,

We are very sorry that you are running into this problem. Often, this happens because you're trying to reset your password with an incorrect username (the UI doesn't tell you if it's wrong or not, it just says it sends an email). You can start the flow of verifying your username, and resetting your password with this form: https://support.sendgrid.com/hc/en-us/requests/new#forgot-username. They will also be able to help you with your invoice issue.

SendGrid Docs Team
