### ISSUE TITLE
Sendgrid not sending emails from gcp

### ISSUE THREAD

**Issue by rajdeep-1981** [sendgrid/docs#4930]
## Actual content

**Link to page**:

**Comment by rajdeep-1981** [comment]
Hello sendgrid support,
Recently we changed the billing details for our gcp platform and after restarting our servers..the emails are not sent out anymore..can you reactivate the services ?

**Comment by Whatthefoxsays** [comment]
Hello rajdeep-1981,

We're sorry you're running into this problem! You can access support contact options by logging into https://support.sendgrid.com.

SendGrid Docs Team

**Comment by thinkingserious** [comment]
Hello @rajdeep-1981,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by rajdeep-1981** [comment]
Thanks for the response..i have managed to resolve the issue..

Thx!!
