### ISSUE TITLE
Not able to login to account

### ISSUE THREAD

**Issue by nitinind91** [sendgrid/docs#4932]
I am not able to login to the account. I cant even contact support via chat or call. I have changed my password but no luck. Not sure if sendgrid is worth evn trying...

**Comment by Whatthefoxsays** [comment]
Hello nitinind91,

We are very sorry that you are running into this problem. Often, this happens because you're trying to reset your password with an incorrect username (the UI doesn't tell you if it's wrong or not, it just says it sends an email). You can start the flow of verifying your username, and resetting your password with this form: https://support.sendgrid.com/hc/en-us/requests/new#forgot-username.

SendGrid Docs Team

**Comment by thinkingserious** [comment]
Hello @nitinind91,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by Imaginedigitalsignage** [comment]
![image](https://user-images.githubusercontent.com/59468482/76827412-68d4a100-6827-11ea-8ecd-372803899ac0.png)

Hi there. I am also experiencing login issues. Please advise?
