### ISSUE TITLE
"Permission denied, wrong credentials"

### ISSUE THREAD

**Issue by vintrix9935** [sendgrid/docs#5235]
I have just created a new account and I tried to use the API directly in the HTTP browser as a test but I am getting this error message: 
{"errors":["Permission denied, wrong credentials"],"message":"error"}

URL used: 
https://api.sendgrid.com/api/mail.send.json?api_user=GxTxMxCxS&api_key=XXXXXX&to=myname@mydomain.com

api_user = username to log into the account
api_key = password to log into the account

Should I be using different credentials for api_user & api_key?

**Comment by Whatthefoxsays** [comment]
Hello @vintrix9935,

We're sorry you're having this issue! Since this is not a docs-related issue, please contact our Support team directly and they can help you out. It also looks like you're using the older version of our API. We recommend using our [v3 API](https://sendgrid.com/docs/api-reference/) instead. You can access support contact options by logging into https://support.sendgrid.com.

SendGrid Docs Team
