### ISSUE TITLE
sending email with multiple content types (text+html)  java

### ISSUE THREAD

**Issue by VikasAmbare** [sendgrid/docs#5302]
## Actual content

**Link to page**:

**Comment by Whatthefoxsays** [comment]
Hello @VikasAmbare,

Seems like you're struggling, but I'm not really sure what your issue is. Since this doesn't seem like a docs-related issue, please contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.

SendGrid Docs Team
