### ISSUE TITLE
Not able to authenticate sendgrid key with wisepops

### ISSUE THREAD

**Issue by sewakram** [sendgrid/docs#5566]
## Actual content

**Not able to authenticate sendgrid key with wisepops getting error like "An error occurred during the authentication. Please check your credentials or contact our support"**:

**Comment by Whatthefoxsays** [comment]
Hello @sewakram 

We're sorry you're having this issue! Since this is not a docs-related issue, please contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.

Otherwise, I found this article on their site, but you might have already seen it: https://support.wisepops.com/en/articles/753257-connect-wisepops-with-sendgrid

If our support team can't help you, I'd also recommend reaching out to Wisepop's support team.

SendGrid Docs Team
