### ISSUE TITLE
Access attempts

### ISSUE THREAD

**Issue by shannonsjackson** [sendgrid/docs#5580]
I am getting these alerts about once a day, Is there somewhere on your website where I can view more information about this? I am trying to track down what the issue is.

This is an IP access alert
An IP address that is not on your whitelist attempted to access your account. shannonj@exigo.com

View Recent Access Attempts

Send with Confidence
© SendGrid Inc. 1801 California Street, Suite 500, Denver, CO 80202 USA
Blog GitHub Twitter Facebook LinkedIn

	 
Email sent using SendGrid.com. 
To unsubscribe click here

## Actual content

**Link to page**:

**Comment by Whatthefoxsays** [comment]
Hello @shannonsjackson

We're sorry you're having this issue! Since this is not a docs-related issue, please contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.

SendGrid Docs Team

**Comment by kzimny** [comment]
I'm having the same problem. As soon as I log in from whitelisted IP address another login attempt from non whitelisted occurs. Contacted SendGrid support but got similar unsatisfied answer. I’m not using 3rd party tools for IP address hiding, VPN’s or proxies. I found that the unauthorized access attempts always happen when I log in from one specific computer in my network.
Logins from other computers in the same network does not cause the unrestricted login attempts. I checked the machine for viruses and spy tools. Nothing suspicious was found. How did you solved the issue?

**Comment by jasonhildebrand** [comment]
I have the same issue as well - when I in from a whitelisted IP address, another login attempt from a non-whitelisted IP occurs soon after.  I, too, suspected malware on my system but have not found anything.  

I am using Chromium.  I'm going to test using a different browser or fresh browser profile, to see if maybe it is due to a malicious browser extension.

**Comment by kzimny** [comment]
The issue has been solved in my case. However, it took a long time. I contacted sendgrid support and send them the log file from my login to sendgrid web account. I tested with fiddler, maybe you are familiar with this tool: https://www.telerik.com/fiddler. When not it's really easy to use. Install fiddler, start it and record only your web login to sendgrid account. Stop recording and search for string "login attempt from a" in the log protocoll. In my case the request that caused the issue came from 3rd party services which are used by sendgrid.com. Strickly speaking from api.sendgrid.com/v3/account/offerings?_show&pricing&_offerings Before you send the fiddler log file to sendgrid support be sure to remove your password from logfile :-) 

![image](https://user-images.githubusercontent.com/12007674/99774867-a607d600-2b0e-11eb-9caf-3be88dd379d9.png)


I hope it will help.
