### ISSUE TITLE
I do not remember my username but if my email if I remember how I recover my account

### ISSUE THREAD

**Issue by CarlangasGO** [sendgrid/docs#5840]
I do not remember my username but if my email if I remember how I recover my account

**Comment by astuteape** [comment]
Hello @CarlangasGO 
You can submit a ticket without your credentials by going to sendgrid.com, scrolling down and choosing "contact support." Then, choose "trouble logging in". I hope this connects you with support, but let me know if you need more help.

**Comment by thinkingserious** [comment]
Hello @CarlangasGO,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by CarlangasGO** [comment]
Thanks, I already sent my request, but there should be a faster way to recover your username and not wait for a ticket system

**Comment by astuteape** [comment]
Thanks @CarlangasGO I'll relay that feedback to the team.
