### ISSUE TITLE
Log file request

### ISSUE THREAD

**Issue by tglaser67** [sendgrid/docs#5873]
I am requesting the access log file for a SendGrid account that was deleted on March 5th.  This request is due to a security related issue.
I also need to request a SendGrid contact for my legal team so they can determine what may be available, such as forensic testing.
The account was owned by EXOS, I am the CISO, Tom Glaser.
SendGrid User name:  cdimeler@teamexos.com

## Actual content

**Link to page**:

**Comment by astuteape** [comment]
Hello @tglaser67  ,
We're sorry you're having this issue! Since this is not a docs-related issue, please contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.

If the deleted account is keeping you from logging in, you can reach support by clicking "Trouble Logging in?". From there, you can tell us a little more about your problem without having to log in, and one of our fantastic support people will get back to you. Hope this helps!
SendGrid Docs Team
