### ISSUE TITLE
Connection could not be established with host smtp.sendgrid.net

### ISSUE THREAD

**Issue by naqibullahmalikzada** [sendgrid/docs#5886]
i am using sendgrid to send mails it works fine in localhost but online it shows this error

`Connection could not be established with host smtp.sendgrid.net :stream_socket_client(): unable to connect to ssl://smtp.sendgrid.net:587 (Permission denied)`
can anyone please help me

**Comment by astuteape** [comment]
Hello @naqibullahmalikzada ,
We're sorry you're having this issue! Since this is not a docs-related issue, please contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.

A few things you might check before submitting your support ticket are:
1. Ensure your environment variables that store your SendGrid credentials are accurate in your non-local setup.
2. Check your config files to be sure your auth is setup correctly to use SSL

Those are just a few guesses based on the error message.
Twilio SendGrid Docs Team
