### ISSUE TITLE
Permission Denied / Unauthorized API call

### ISSUE THREAD

**Issue by tarantej** [sendgrid/docs#6059]
I am a trying to test run the sendgrid API with my python code. I get the code from the Documentation but It is showing unauthorized even though I created the API key using the steps

## Expected content

A sample email is recieved in my inbox

## Actual content

{
    "errors": [
        {
            "message": "Permission denied, wrong credentials",
            "field": null,
            "help": null
        }
    ]
}

**Link to page**:

**Comment by astuteape** [comment]
Hello @tarantej ,

We're sorry you're having this issue! You might try trouble shooting your API key by making the API call with your key in a tool like Postman. That would at least help you determine if the problem is caused by the code you're using to pass the key along. For more one-on-one assistance, please contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.

Twilio SendGrid Docs Team
