### ISSUE TITLE
Emails not sending 

### ISSUE THREAD

**Issue by BJKea-ctca** [sendgrid/docs#6126]
## Expected content
Emails being sent

## Actual content
Response code of 200Ok but no emails delivered

Hanna asked me to open a ticket but there is no where under support to do that so I am opening it here

**Comment by Whatthefoxsays** [comment]
Hello <name> ,

We're sorry you're having this issue! Since this is not a docs-related issue, please contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com. You'll need to log in to create a ticket, or if you're unable to log in, click **Trouble Logging in?**.

The Twilio SendGrid Docs Team

**Comment by BJKea-ctca** [comment]
I did contact Hanna at support and she told me to open an issue that … you just closed.  WHY!?!?!?!?!?




[CTCA-logo2]
BJ Kea
Information Services / Application Developer
Cancer Treatment Centers of America
676 N. 137th Avenue, Goodyear, Arizona 85338
O: (623)207-3765
E: william.kea@ctca-hope.com<mailto:william.kea@ctca-hope.com>  W: cancercenter.com<https://www.cancercenter.com/>
Hospitals<https://www.cancercenter.com/locations?loc=hospitals> | Outpatient Care Centers<https://www.cancercenter.com/locations?loc=clinics>
The information contained in this communication is confidential and does not apply to anyone other than the intended recipient. If the reader of this communication is not the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please notify me immediately by reply e-mail or telephone and destroy all copies of the original message.
