### ISSUE TITLE
Cannot upgrade plan because warning message 

### ISSUE THREAD

**Issue by chitampopo** [sendgrid/docs#6182]
## Expected content
I can select options in the Essentials plan at the link https://app.sendgrid.com/account/billing/choose_plan without any warning message

Or provide more information on how I can pass the warning message

## Actual content
Warning message in the top of page
![2020-08-07_18h34_21](https://user-images.githubusercontent.com/9018326/89641836-c8b60c00-d8dc-11ea-83a5-7c3d30c77a57.png)

**Link to page**:
https://app.sendgrid.com/account/billing/choose_plan

Moreover, my team also sent a support ticket with number 4862331. Please help because it's our impediment

**Comment by astuteape** [comment]
Hello @chitampopo 

We have started implementing more frequent review of user account upgrades. We apologize that this wasn't communicated more clearly in our documentation. We will update to the docs soon so that this is clear.

Thank you for opening the support ticket. We will follow up with support and ask them to reach out if they have not done so already.

Best,

Twilio SendGrid Docs Team

**Comment by adriancable** [comment]
Same issue here - account is adrian@starlinghome.io - how do I proceed? Support tickets are not being responded to.

**Comment by chitampopo** [comment]
We can only upgrade the account after 30 days from the created day.
