### ISSUE TITLE
Ip banned

### ISSUE THREAD

**Issue by henaff** [sendgrid/docs#6275]
Banned for phishing since 5 days...

50.31.49.41

https://www.spamhaus.org/sbl/listings/sendgrid.com

```
550 5.7.1 Service unavailable, Client host [50.31.49.41] blocked using Spamhaus. To request removal from this list see https://www.spamhaus.org/query/ip/50.31.49.41 (AS3130). [VE1EUR01FT062.eop-EUR01.prod.protection.outlook.com]
```

```
550 5.7.1 Mail from IP 50.31.49.41 was rejected due to listing in Spamhaus SBL. For details please see http://www.spamhaus.org/query/bl?ip=50.31.49.41
```

```
451 4.7.650 The mail server [167.89.12.138] has been temporarily rate limited due to IP reputation. For e-mail delivery information, see https://postmaster.live.com (S3113) [VI1EUR06FT038.eop-eur06.prod.protection.outlook.com]
```

```
550 5.7.1 Service unavailable, Client host [50.31.49.42] blocked using Spamhaus. To request removal from this list see https://www.spamhaus.org/query/ip/50.31.49.42 (AS3130). [VI1EUR05FT033.eop-eur05.prod.protection.outlook.com]
```

**Comment by astuteape** [comment]
Hi @henaff 

Thank you for submitting this issue. We want to assure you that we’re working closely with Spamhaus to resolve the addresses listed on their site and lift any blocks. We’re making progress and communicating with Spamhaus on a daily basis. There’s a good chance that this blacklisting may already have been resolved. To check the status of your IP address, you can visit https://www.spamhaus.org/lookup/ and enter the affected IP address. We appreciate how this could be frustrating but please know that Spamhaus will only communicate with our internal Twilio SendGrid teams regarding delisting. Thank you for your patience while we work with Spamhaus to resolve this situation.

Because the issue cannot be addressed directly in the documentation, we will be closing this issue. Thank you again for your patience.

Twilio SendGrid Docs Team
