### ISSUE TITLE
signup cannot be done

### ISSUE THREAD

**Issue by Manimojy** [sendgrid/docs#6287]
## Expected content
signup should be done

## Actual content
cannot signup . checked the inspector and in the firefox console this is the error message
Access to manifest at 'https://sendgrid.com/brand/favicons/manifest.json' from origin 'https://signup.sendgrid.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
**Link to page**:
https://signup.sendgrid.com/

**Comment by Manimojy** [comment]
I tried to signup in chrome and when I clicked the "I'm not a robot" checkbox The following error shows in the console:
Access to fetch at 'https://api.sendgrid.com/v3/public/s2s/signup/recaptcha_verify' from origin 'https://signup.sendgrid.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by astuteape** [comment]
Hello @Manimojy 

We're sorry you had this issue! We missed this at the time. Since this is not a docs-related issue, we hope you were able to contact our Support team directly for help. You can always access support contact options by logging into https://support.sendgrid.com.

Twilio SendGrid Docs Team
