### ISSUE TITLE
Interactive Guide for stats/category returning wrong response body

### ISSUE THREAD

**Issue by asiSendGrid** [sendgrid/docs#632]
https://sendgrid.com/docs/API_Reference/Web_API/Statistics/index.html

When using the interactive documentation, the api call being made is incomplete. The response body is only stats when it should be category list. I believe the list param is missing when the call is being made.

**Comment by trotha01** [comment]
@mbernier It looks like we use the 'apiexample' function [here](https://github.com/sendgrid/docs/blob/develop/source/API_Reference/Web_API/Statistics/index.html#L127), and list=true is passed in: 

But it seems like "list=true" still is not in the request body when the request is made?

I tried looking at where the [apiexample code](https://github.com/sendgrid/docs/blob/6fcf2a5056ee9f1c6fbc6584ed285d5cae485af8/plugins/apiexample.rb#L70) deals with the request data, and the [requestblock code](https://github.com/sendgrid/docs/blob/74a3791d2416117a13e5ab1d557b45158b7a0700/plugins/requestblock.rb#L95), but still couldn't figure out how to change it so that "list=true" ends up in the request.

I could definitely be looking in the wrong places. Maybe @brandonmwest might know more on this?

**Comment by mbernier** [comment]
I believe that what is going on is that in [apiexample plugin](https://github.com/sendgrid/docs/blob/develop/plugins/apiexample.rb#L22) we pass the data to livedoc, but then in livedoc [we don't parse the params out of the liquid tag](https://github.com/sendgrid/docs/blob/develop/plugins/livedocs.rb#L12).  My thought is that it was built this way to avoid conflict when a param table is available and data is entered.

**Comment by thinkingserious** [comment]
Hello @asiSendGrid,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
