### ISSUE TITLE
Bounce Type = Expired causing confusion for customers

### ISSUE THREAD

**Issue by Reformant** [sendgrid/docs#702]
Hey guys,

Any info on the "Expired" type of bounce you know of?
https://sendgrid.com/docs/API_Reference/Webhooks/event.html#-Bounce

**Comment by ksigler7** [comment]
Reopening this to hijack it for creating a glossary entry for "Expired"

**Comment by duncanleung** [comment]
Hi @ksigler7, I can take this too.

**To clarify the steps to resolve this issue:**
- Create a new Glossary Entry for "Expired"
- Link Bounce Event "Expired", to this new Glossary Entry (related to issue #2734)

**Terminology Clarification:**
I wanted to clarify, what is the definition of 'Bounce - Expired'? I don't see any information on the SendGrid docs site after searching around.

I find two possible reasons for 'Bounce - Expired' emails
https://support.intouchcrm.com/articles/email/what-are-email-bounces

1. The message bounced due to an expired, inactive, or disabled recipient address, **5.X.X** error.
2. The message bounced due to not being delivered before the two day window in which the system continues to attempt delivery, **4.X.X** error.

How does SendGrid denote a, Bounce - Expired, message?

Thanks

**Comment by duncanleung** [comment]
@mbernier @ksigler7 

Just pinging to see if you could provide some comments on my previous question?

I wanted to clarify how SendGrid categorizes **'Bounce - Expired'**.

Two possible definitions that I found online, relating to message sending, are:

1. The message bounced due to an expired, inactive, or disabled recipient address, **5.X.X** error.
2. The message bounced due to not being delivered before the two day window in which the system continues to attempt delivery, **4.X.X** error.

Thanks!

**Comment by kylearoberts** [comment]
Hello @duncanleung 
Sorry for our delay. Bounce - Expired in general means we were unable to deliver the email in the last 72 hours. Now there are some 5.X.X and 4.X.X that can result in an instance where we try for up to 72 hours to deliver email. So I would say that both your examples are correct.  Additional examples I have seen include:
- Domain frequency limited. 
- Connection frequency limited. 
- Too many invalid recipients
- Ip frequency limited.
Which are all 550 errors.

I hope this helps and please let us know if there are further questions.

**Comment by ksigler7** [comment]
This turned out really well @duncanleung, thanks so much for writing this up!

And thanks again for answering the question @kylearoberts :)

**Comment by duncanleung** [comment]
@ksigler7 awesome! Glad to hear!

Thanks to @kylearoberts for the support!
